PRAGMA foreign_keys = ON;

CREATE TABLE inventory (
    stable_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    location TEXT NOT NULL,
    status TEXT NOT NULL,
    item_date TEXT,
    category TEXT NOT NULL,
    unit TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    bin TEXT NOT NULL,
    retention_class TEXT NOT NULL,
    handling_notes TEXT NOT NULL
);

CREATE TABLE notifications (
    sequence INTEGER PRIMARY KEY AUTOINCREMENT,
    item_id TEXT NOT NULL,
    message TEXT NOT NULL,
    FOREIGN KEY (item_id) REFERENCES inventory(stable_id)
);

CREATE TABLE execution_journal (
    sequence INTEGER PRIMARY KEY AUTOINCREMENT,
    operation TEXT NOT NULL,
    arguments_json TEXT NOT NULL,
    started_ns INTEGER NOT NULL,
    pid INTEGER NOT NULL,
    parent_pid INTEGER NOT NULL,
    finished_ns INTEGER,
    result_count INTEGER,
    sole_id TEXT,
    result_digest TEXT,
    violation INTEGER NOT NULL DEFAULT 0,
    error TEXT
);

INSERT INTO inventory
    (stable_id, name, location, status, item_date, category, unit,
     quantity, bin, retention_class, handling_notes)
VALUES
    ('inv_7Q4M9X2C', 'Archival Packing Tape', 'Warehouse C', 'active',
     NULL, 'preservation supply', 'roll', 184, 'C-17-04',
     'standard', 'Keep dry and below 27 C.'),
    ('inv_7Q4M9X2B', 'Archival Packing Tape', 'Warehouse B', 'pending',
     '2026-06-13', 'preservation supply', 'roll', 96, 'B-08-11',
     'standard', 'Awaiting adhesive quality review.'),
    ('inv_7Q4M9X2D', 'Archival Packing Tape', 'Warehouse D', 'archived',
     '2025-11-22', 'preservation supply', 'roll', 0, 'D-02-09',
     'legacy', 'Superseded stock record.'),
    ('inv_7Q4M9X2A', 'Archival Packing Tape', 'Warehouse A', 'active',
     '2026-06-12', 'preservation supply', 'roll', 211, 'A-10-03',
     'standard', 'Keep cartons sealed between picks.'),
    ('inv_7Q4M9X3C', 'Archival Packing Tapes', 'Warehouse C', 'active',
     '2026-06-15', 'preservation supply', 'case', 12, 'C-17-05',
     'standard', 'Plural-name bulk case record.'),
    ('inv_7Q4N9X2C', 'Archival Packaging Tape', 'Warehouse C', 'pending',
     '2026-06-16', 'packing supply', 'roll', 44, 'C-17-06',
     'standard', 'Packaging trial stock.'),
    ('inv_7Q4M9Y2C', 'Archive Packing Tape', 'Warehouse C', 'active',
     '2026-06-17', 'packing supply', 'roll', 61, 'C-17-07',
     'standard', 'Different display name.'),
    ('inv_7Q4M9X2E', 'Archival Packing Tape - Wide', 'Warehouse C', 'active',
     '2026-06-18', 'preservation supply', 'roll', 37, 'C-17-08',
     'standard', 'Wide format rolls.'),
    ('inv_7Q4M9X2F', 'Archival Packing Tape', 'Warehouse C Annex', 'archived',
     '2025-10-04', 'preservation supply', 'roll', 0, 'CA-01-01',
     'legacy', 'Annex record; location is distinct.'),
    ('inv_7Q4M9X2G', 'Archival Packing Tape', 'Warehouse C Returns', 'pending',
     '2026-06-19', 'preservation supply', 'roll', 9, 'CR-03-02',
     'review', 'Returned rolls awaiting inspection.'),
    ('inv_7Q4M9X2H', 'Archival Packing Tape (Old)', 'Warehouse C', 'archived',
     '2024-12-09', 'preservation supply', 'roll', 0, 'C-99-01',
     'legacy', 'Historical name with suffix.'),
    ('inv_7Q4M9X2I', 'ArchivaI Packing Tape', 'Warehouse C', 'active',
     '2026-06-20', 'preservation supply', 'roll', 23, 'C-17-09',
     'standard', 'Display name contains an uppercase I.'),
    ('inv_7Q4M9X2J', 'Archival Packing-Tape', 'Warehouse C', 'pending',
     '2026-06-21', 'preservation supply', 'roll', 18, 'C-17-10',
     'review', 'Hyphenated display name.'),
    ('inv_7Q4M9X2K', 'Acid-Free Document Sleeves', 'Warehouse C', 'active',
     '2026-05-03', 'preservation supply', 'box', 75, 'C-11-01',
     'standard', 'Letter-size sleeves.'),
    ('inv_7Q4M9X2L', 'Acid-Free Document Sleeves', 'Warehouse A', 'pending',
     '2026-05-04', 'preservation supply', 'box', 32, 'A-11-01',
     'standard', 'Transfer awaiting count.'),
    ('inv_7Q4M9X2M', 'Buffered Tissue Paper', 'Warehouse B', 'active',
     '2026-05-05', 'preservation supply', 'ream', 48, 'B-12-02',
     'standard', 'Use for interleaving.'),
    ('inv_7Q4M9X2N', 'Buffered Tissue Paper', 'Warehouse C', 'archived',
     '2025-08-14', 'preservation supply', 'ream', 0, 'C-12-02',
     'legacy', 'Retired stock entry.'),
    ('inv_7Q4M9X2P', 'Polyethylene Storage Bags', 'Warehouse D', 'active',
     '2026-05-07', 'storage supply', 'case', 19, 'D-14-06',
     'standard', 'Assorted sizes.'),
    ('inv_7Q4M9X2Q', 'Polyethylene Storage Bags', 'Warehouse C', 'pending',
     '2026-05-08', 'storage supply', 'case', 8, 'C-14-06',
     'review', 'Pending seam inspection.'),
    ('inv_7Q4M9X2R', 'Cotton Handling Gloves', 'Warehouse A', 'active',
     '2026-05-09', 'handling supply', 'pair', 340, 'A-04-08',
     'standard', 'Unbleached cotton.'),
    ('inv_7Q4M9X2S', 'Cotton Handling Gloves', 'Warehouse C', 'archived',
     '2025-09-30', 'handling supply', 'pair', 0, 'C-04-08',
     'legacy', 'Archived size mix.'),
    ('inv_7Q4M9X2T', 'Nitrile Handling Gloves', 'Warehouse C', 'active',
     '2026-05-11', 'handling supply', 'box', 57, 'C-04-09',
     'standard', 'Powder-free medium.'),
    ('inv_7Q4M9X2U', 'Document Repair Tissue', 'Warehouse B', 'pending',
     '2026-05-12', 'repair supply', 'pack', 14, 'B-15-03',
     'review', 'Awaiting conservator approval.'),
    ('inv_7Q4M9X2V', 'Document Repair Tissue', 'Warehouse D', 'active',
     '2026-05-13', 'repair supply', 'pack', 27, 'D-15-03',
     'controlled', 'Issue only to repair bench.'),
    ('inv_7Q4M9X2W', 'Neutral pH Adhesive', 'Warehouse C', 'active',
     '2026-05-14', 'repair supply', 'bottle', 33, 'C-15-05',
     'controlled', 'Rotate stock by received date.'),
    ('inv_7Q4M9X2X', 'Neutral pH Adhesive', 'Warehouse A', 'archived',
     '2025-07-18', 'repair supply', 'bottle', 0, 'A-15-05',
     'legacy', 'Expired batch record.'),
    ('inv_7Q4M9X2Y', 'Corrugated Archive Cartons', 'Warehouse C', 'pending',
     '2026-05-16', 'storage supply', 'bundle', 22, 'C-21-02',
     'standard', 'Count validation in progress.'),
    ('inv_7Q4M9X2Z', 'Corrugated Archive Cartons', 'Warehouse B', 'active',
     '2026-05-17', 'storage supply', 'bundle', 41, 'B-21-02',
     'standard', 'Flat packed.'),
    ('inv_7Q4M9X20', 'Photo Storage Envelopes', 'Warehouse D', 'archived',
     '2025-06-01', 'storage supply', 'box', 0, 'D-22-07',
     'legacy', 'Superseded envelope size.'),
    ('inv_7Q4M9X21', 'Photo Storage Envelopes', 'Warehouse C', 'active',
     '2026-05-19', 'storage supply', 'box', 66, 'C-22-07',
     'standard', 'PAT-passed stock.'),
    ('inv_7Q4M9X22', 'Unbuffered Interleaving Paper', 'Warehouse A', 'pending',
     '2026-05-20', 'preservation supply', 'ream', 29, 'A-18-04',
     'review', 'Supplier certificate pending.'),
    ('inv_7Q4M9X23', 'Unbuffered Interleaving Paper', 'Warehouse C', 'active',
     '2026-05-21', 'preservation supply', 'ream', 52, 'C-18-04',
     'standard', 'For photographic materials.'),
    ('inv_7Q4M9X24', 'Polyester Film Sheets', 'Warehouse B', 'archived',
     '2025-04-12', 'preservation supply', 'pack', 0, 'B-16-01',
     'legacy', 'Old gauge stock.'),
    ('inv_7Q4M9X25', 'Polyester Film Sheets', 'Warehouse C', 'active',
     '2026-05-23', 'preservation supply', 'pack', 38, 'C-16-01',
     'standard', 'Clear archival polyester.'),
    ('inv_7Q4M9X26', 'Book Cradle Foam', 'Warehouse D', 'pending',
     '2026-05-24', 'handling supply', 'set', 11, 'D-07-03',
     'review', 'Density check pending.'),
    ('inv_7Q4M9X27', 'Book Cradle Foam', 'Warehouse C', 'active',
     '2026-05-25', 'handling supply', 'set', 24, 'C-07-03',
     'standard', 'Mixed wedge sizes.'),
    ('inv_7Q4M9X28', 'Tyvek Roll Stock', 'Warehouse A', 'active',
     '2026-05-26', 'covering supply', 'roll', 17, 'A-19-02',
     'standard', 'Store upright.'),
    ('inv_7Q4M9X29', 'Tyvek Roll Stock', 'Warehouse C', 'archived',
     '2025-02-03', 'covering supply', 'roll', 0, 'C-19-02',
     'legacy', 'Damaged-roll lot closed.'),
    ('inv_7Q4M9X30', 'Microspatula Set', 'Warehouse B', 'active',
     '2026-05-28', 'tool', 'set', 13, 'B-06-10',
     'controlled', 'Sign out per bench.'),
    ('inv_7Q4M9X31', 'Microspatula Set', 'Warehouse C', 'pending',
     '2026-05-29', 'tool', 'set', 7, 'C-06-10',
     'review', 'Set completeness check pending.');
