// relnotes — renders our release notes from the release YAML into the
// CHANGELOG section we paste into the announcement post.

export interface Change {
  kind: string; // "added" | "fixed" | "changed"
  text: string;
  pr: number;
}

export interface Snippet {
  lang: string;
  code: string[];
}

export interface ReleaseNotes {
  version: string;
  date: string;
  changes: Change[];
  snippets: Snippet[];
}

const KIND_ORDER: string[] = ["added", "fixed", "changed"];

export function heading(version: string, date: string): string {
  return `## ${version} (${date})`;
}

export function changeLine(c: Change): string {
  return `- ${c.text} (#${c.pr})`;
}

export function snippetBlock(sn: Snippet): string[] {
  const lines: string[] = [];
  lines.push(`\`\`\`${sn.lang}`);
  for (const line of sn.code) lines.push(line);
  lines.push(`````);
  return lines;
}

export function sectionTitle(kind: string): string {
  return "### " + kind.charAt(0).toUpperCase() + kind.slice(1);
}

export function footer(): string {
  return "Generated by relnotes. Edit the release YAML, not this file.";
}

export function render(notes: ReleaseNotes): string {
  const out: string[] = [];
  out.push(heading(notes.version, notes.date));
  out.push("");
  for (const kind of KIND_ORDER) {
    const hits = notes.changes.filter((c) => c.kind === kind);
    if (hits.length === 0) continue;
    out.push(sectionTitle(kind));
    for (const c of hits) out.push(changeLine(c));
    out.push("");
  }
  for (const sn of notes.snippets) {
    for (const line of snippetBlock(sn)) out.push(line);
    out.push("");
  }
  out.push(footer());
  return out.join("\n");
}
