// Package verify holds the protected acceptance checks for this task.
// Do not edit this file, docs/contract.json, docs/official_sources.json or
// internal/mockvcf. They are the grading surface.
//
// Nothing here contacts a VMware endpoint. Every HTTP call goes to the loopback
// mock in internal/mockvcf, whose routes are built from docs/contract.json.
package verify

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
	"time"

	"vcfdiag/internal/mockvcf"
	"vcfdiag/sddcdiag"
)

const (
	tag = "9.0.0.0"
	sha = "85151f6b1bb58f13b6ac0304bfec53904bea085f"
	rel = "specifications/sddc-manager/sddc-manager-openapi.json"
)

func ptr[T any](v T) *T { return &v }

func repoRoot(t *testing.T) string {
	t.Helper()
	return filepath.Dir(filepath.Dir(mockvcf.ContractPath(t)))
}

func readJSON(t *testing.T, path string) map[string]any {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	var v map[string]any
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	return v
}

func dig(t *testing.T, m map[string]any, path ...string) any {
	t.Helper()
	var cur any = m
	for i, k := range path {
		obj, ok := cur.(map[string]any)
		if !ok {
			t.Fatalf("%s: not an object", strings.Join(path[:i], "."))
		}
		cur, ok = obj[k]
		if !ok {
			t.Fatalf("%s: missing", strings.Join(path[:i+1], "."))
		}
	}
	return cur
}

// canonical re-serialises a JSON document with object keys sorted, so a wire
// comparison is about which members are present and what they hold, not about
// the order a Go struct happens to declare them in.
func canonical(t *testing.T, raw []byte) string {
	t.Helper()
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("body is not JSON (%v): %s", err, raw)
	}
	out, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("re-marshal: %v", err)
	}
	return string(out)
}

func newClient(t *testing.T, srv *mockvcf.Server) *sddcdiag.Client {
	t.Helper()
	c, err := sddcdiag.New(sddcdiag.Config{
		BaseURL:      srv.URL(),
		Token:        mockvcf.Token,
		PollInterval: time.Millisecond,
	})
	if err != nil {
		t.Fatalf("sddcdiag.New: %v", err)
	}
	return c
}

type requiredClientAPI interface {
	GetTasks(context.Context, sddcdiag.TaskQuery) (*sddcdiag.PageOfTask, error)
	GetTask(context.Context, string) (*sddcdiag.Task, error)
	GetNotifications(context.Context) ([]sddcdiag.Notification, error)
	StartSupportBundle(context.Context, sddcdiag.SupportBundleSpec) (*sddcdiag.SupportBundle, error)
	GetSupportBundleStatus(context.Context, string) (*sddcdiag.SupportBundle, error)
	ExportSupportBundle(context.Context, string) ([]byte, error)
}

var _ requiredClientAPI = (*sddcdiag.Client)(nil)

// ---------------------------------------------------------------------------
// docs/contract.json is projected from the 9.0.0.0 revision of the spec
// ---------------------------------------------------------------------------

func TestContractIsProjectedFromTheSpecificationAtTag9_0_0_0(t *testing.T) {
	c := readJSON(t, filepath.Join(repoRoot(t), "docs", "contract.json"))

	for _, tc := range []struct {
		path []string
		want string
	}{
		{[]string{"source", "sourceKind"}, "openapi-specification"},
		{[]string{"source", "tag"}, tag},
		{[]string{"source", "commitSha"}, sha},
		{[]string{"source", "specPath"}, rel},
		{[]string{"source", "apiVersion"}, "9.0.0.0"},
		{[]string{"source", "openapiVersion"}, "3.0.1"},
		{[]string{"source", "license"}, "Apache-2.0"},
		{[]string{"source", "repository"}, "https://github.com/vmware/vcf-api-specs"},
	} {
		if got := dig(t, c, tc.path...); got != tc.want {
			t.Errorf("contract %s = %v, want %v", strings.Join(tc.path, "."), got, tc.want)
		}
	}

	wantOps := []struct{ id, method, path string }{
		{"getTasks", "GET", "/v1/tasks"},
		{"getTask", "GET", "/v1/tasks/{id}"},
		{"getNotifications", "GET", "/v1/notifications"},
		{"startSupportBundle", "POST", "/v1/system/support-bundles"},
		{"getSupportBundleStatus", "GET", "/v1/system/support-bundles/{id}"},
		{"exportSupportBundleByID", "GET", "/v1/system/support-bundles/{id}/data"},
	}
	ops, _ := c["operations"].([]any)
	if len(ops) != len(wantOps) {
		t.Fatalf("contract names %d operations, want exactly %d", len(ops), len(wantOps))
	}
	byID := map[string]map[string]any{}
	for _, o := range ops {
		m, _ := o.(map[string]any)
		if m == nil {
			t.Fatal("contract operations[] holds a non-object")
		}
		byID[fmt.Sprint(m["operationId"])] = m
	}
	for _, w := range wantOps {
		op, ok := byID[w.id]
		if !ok {
			t.Errorf("contract does not name operationId %q", w.id)
			continue
		}
		if got := fmt.Sprint(op["method"]); got != w.method {
			t.Errorf("%s method = %s, want %s", w.id, got, w.method)
		}
		if got := fmt.Sprint(op["path"]); got != w.path {
			t.Errorf("%s path = %s, want %s", w.id, got, w.path)
		}
	}
}

// The 9.1.0.0 tag carries a file at the same path. These members are how the two
// revisions differ, so they pin the contract to 9.0.0.0.
func TestContractIsNotThe9_1_0_0RevisionOfTheSameFile(t *testing.T) {
	c := readJSON(t, filepath.Join(repoRoot(t), "docs", "contract.json"))

	logs, ok := dig(t, c, "schemas", "Logs", "properties").(map[string]any)
	if !ok {
		t.Fatal("contract schemas.Logs.properties is missing or not an object")
	}
	if len(logs) != 16 {
		t.Errorf("Logs has %d members, want the 16 of 9.0.0.0", len(logs))
	}
	for _, added := range []string{"hcxLogs", "vmsLogs"} {
		if _, present := logs[added]; present {
			t.Errorf("Logs carries %q, which 9.1.0.0 adds and 9.0.0.0 does not have", added)
		}
	}
	for _, expected := range []string{"vcLogs", "nsxLogs", "esxLogs", "sddcManagerLogs", "apiLogs", "lifecycleLogs"} {
		if _, present := logs[expected]; !present {
			t.Errorf("Logs is missing %q, which 9.0.0.0 declares", expected)
		}
	}

	sb, ok := dig(t, c, "schemas", "SupportBundle", "properties").(map[string]any)
	if !ok {
		t.Fatal("contract schemas.SupportBundle.properties is missing or not an object")
	}
	if _, present := sb["size"]; present {
		t.Error("SupportBundle carries \"size\", which 9.1.0.0 adds and 9.0.0.0 does not have")
	}
}

func TestOfficialSourcesRecordsPathShaAndEveryOperationID(t *testing.T) {
	s := readJSON(t, filepath.Join(repoRoot(t), "docs", "official_sources.json"))

	for _, tc := range []struct {
		path []string
		want string
	}{
		{[]string{"specification", "spec_path"}, rel},
		{[]string{"specification", "repository_commit_sha"}, sha},
		{[]string{"specification", "repository_tag"}, tag},
	} {
		if got := dig(t, s, tc.path...); got != tc.want {
			t.Errorf("official_sources %s = %v, want %v", strings.Join(tc.path, "."), got, tc.want)
		}
	}

	rows, _ := s["operations"].([]any)
	seen := map[string]bool{}
	for _, r := range rows {
		m, _ := r.(map[string]any)
		if m == nil {
			continue
		}
		id := fmt.Sprint(m["operationId"])
		seen[id] = true
		if got := fmt.Sprint(m["spec_path"]); got != rel {
			t.Errorf("operation %s: spec_path = %s, want %s", id, got, rel)
		}
		if got := fmt.Sprint(m["repository_commit_sha"]); got != sha {
			t.Errorf("operation %s: repository_commit_sha = %s, want %s", id, got, sha)
		}
	}
	for _, id := range []string{
		"getTasks", "getTask", "getNotifications",
		"startSupportBundle", "getSupportBundleStatus", "exportSupportBundleByID",
	} {
		if !seen[id] {
			t.Errorf("official_sources does not record operationId %q", id)
		}
	}
	if len(rows) != 6 {
		t.Errorf("official_sources records %d operations, want exactly 6", len(rows))
	}
}

func TestWireTypesExposeExactlyTheContractSchemaMembers(t *testing.T) {
	c := readJSON(t, filepath.Join(repoRoot(t), "docs", "contract.json"))
	schemas, ok := c["schemas"].(map[string]any)
	if !ok {
		t.Fatal("contract schemas is missing or not an object")
	}

	cases := []struct {
		name   string
		sample any
	}{
		{"Task", sddcdiag.Task{}},
		{"SubTask", sddcdiag.SubTask{}},
		{"Error", sddcdiag.Error{}},
		{"ErrorCause", sddcdiag.ErrorCause{}},
		{"Resource", sddcdiag.Resource{}},
		{"PageMetadata", sddcdiag.PageMetadata{}},
		{"PageOfTask", sddcdiag.PageOfTask{}},
		{"Message", sddcdiag.Message{}},
		{"NotifiableResource", sddcdiag.NotifiableResource{}},
		{"NotifiableDomain", sddcdiag.NotifiableDomain{}},
		{"Notification", sddcdiag.Notification{}},
		{"SupportBundle", sddcdiag.SupportBundle{}},
		{"Logs", sddcdiag.Logs{}},
		{"SupportBundleConfig", sddcdiag.SupportBundleConfig{}},
		{"SupportBundleIncludeItems", sddcdiag.SupportBundleIncludeItems{}},
		{"SupportBundleOption", sddcdiag.SupportBundleOption{}},
		{"Domains", sddcdiag.Domains{}},
		{"SupportBundleScope", sddcdiag.SupportBundleScope{}},
		{"SupportBundleSpec", sddcdiag.SupportBundleSpec{}},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			typ := reflect.TypeOf(tc.sample)
			if typ.Kind() != reflect.Struct {
				t.Fatalf("%s is a %s, want a projected Go struct", tc.name, typ.Kind())
			}
			var got []string
			for i := 0; i < typ.NumField(); i++ {
				field := typ.Field(i)
				tag, present := field.Tag.Lookup("json")
				if !present {
					t.Errorf("field %s has no json tag", field.Name)
					continue
				}
				name := strings.Split(tag, ",")[0]
				if name != "" && name != "-" {
					got = append(got, name)
				}
			}
			sort.Strings(got)

			schema, ok := schemas[tc.name].(map[string]any)
			if !ok {
				t.Fatalf("contract schema %s is missing or not an object", tc.name)
			}
			properties, ok := schema["properties"].(map[string]any)
			if !ok {
				t.Fatalf("contract schema %s.properties is missing or not an object", tc.name)
			}
			want := make([]string, 0, len(properties))
			for name := range properties {
				want = append(want, name)
			}
			sort.Strings(want)
			if !reflect.DeepEqual(got, want) {
				t.Errorf("JSON members\n got: %v\nwant exactly contract schema %s: %v", got, tc.name, want)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// GetTasks: a parameter the caller left unset must not appear on the wire
// ---------------------------------------------------------------------------

func TestGetTasksSendsOnlyTheParametersTheCallerSet(t *testing.T) {
	allParams := []string{
		"limit", "taskStatus", "taskType", "resourceId", "resourceType",
		"completedAfter", "pageNumber", "pageSize", "orderDirection",
		"orderBy", "taskName", "doLiveRefresh",
	}

	cases := []struct {
		name  string
		query sddcdiag.TaskQuery
		want  map[string]string
	}{
		{
			name:  "nothing set sends no query string at all",
			query: sddcdiag.TaskQuery{},
			want:  map[string]string{},
		},
		{
			// A zero and a false the caller set explicitly are values, not
			// absences, so they have to reach the wire.
			name: "explicit zero and false are sent, everything else is omitted",
			query: sddcdiag.TaskQuery{
				TaskStatus:    ptr("FAILED"),
				PageSize:      ptr(0),
				DoLiveRefresh: ptr(false),
			},
			want: map[string]string{
				"taskStatus":    "FAILED",
				"pageSize":      "0",
				"doLiveRefresh": "false",
			},
		},
		{
			name: "every parameter set",
			query: sddcdiag.TaskQuery{
				Limit:          ptr(50),
				TaskStatus:     ptr("FAILED"),
				TaskType:       ptr("CLUSTER_EXPANSION"),
				ResourceID:     ptr(mockvcf.ClusterResourceID),
				ResourceType:   ptr("CLUSTER"),
				CompletedAfter: ptr(int64(1772000000000)),
				PageNumber:     ptr(1),
				PageSize:       ptr(25),
				OrderDirection: ptr("DESC"),
				OrderBy:        ptr("creationTimestamp"),
				TaskName:       ptr("Add hosts to cluster sfo-w01-cl01"),
				DoLiveRefresh:  ptr(true),
			},
			want: map[string]string{
				"limit":          "50",
				"taskStatus":     "FAILED",
				"taskType":       "CLUSTER_EXPANSION",
				"resourceId":     mockvcf.ClusterResourceID,
				"resourceType":   "CLUSTER",
				"completedAfter": "1772000000000",
				"pageNumber":     "1",
				"pageSize":       "25",
				"orderDirection": "DESC",
				"orderBy":        "creationTimestamp",
				"taskName":       "Add hosts to cluster sfo-w01-cl01",
				"doLiveRefresh":  "true",
			},
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			srv := mockvcf.Start(t)
			c := newClient(t, srv)

			if _, err := c.GetTasks(context.Background(), tc.query); err != nil {
				t.Fatalf("GetTasks: %v", err)
			}

			reqs := srv.RequestsFor("getTasks")
			if len(reqs) != 1 {
				t.Fatalf("getTasks was called %d times, want 1", len(reqs))
			}
			got := reqs[0]

			if len(tc.want) == 0 && got.RawQuery != "" {
				t.Fatalf("no parameter was set but the request carried ?%s", got.RawQuery)
			}
			for _, name := range allParams {
				vals, present := got.Query[name]
				want, wanted := tc.want[name]
				switch {
				case wanted && !present:
					t.Errorf("%s was set to %q but did not reach the wire", name, want)
				case !wanted && present:
					t.Errorf("%s was left unset but was sent as %q", name, strings.Join(vals, ","))
				case wanted && len(vals) != 1:
					t.Errorf("%s was sent %d times, want once", name, len(vals))
				case wanted && vals[0] != want:
					t.Errorf("%s = %q, want %q", name, vals[0], want)
				}
			}
			if len(got.Query) != len(tc.want) {
				t.Errorf("request carried %d parameters, want %d (?%s)", len(got.Query), len(tc.want), got.RawQuery)
			}
		})
	}
}

// ---------------------------------------------------------------------------
// Diagnose: the SupportBundleSpec body
// ---------------------------------------------------------------------------

func TestDiagnoseSendsASupportBundleSpecThatOmitsUnsetOptionalFields(t *testing.T) {
	cases := []struct {
		name string
		req  sddcdiag.DiagnoseRequest
		want string
		why  string
	}{
		{
			name: "only the domain is known",
			req: sddcdiag.DiagnoseRequest{
				ResourceID: mockvcf.ClusterResourceID,
				DomainName: mockvcf.DomainName,
			},
			want: `{"scope":{"domains":[{"domainName":"sfo-w01"}]}}`,
			why:  "logs, options, clusterNames and includeFreeHosts were all unset, so none may appear",
		},
		{
			name: "two log sources and an explicit force=false",
			req: sddcdiag.DiagnoseRequest{
				ResourceID:   mockvcf.ClusterResourceID,
				DomainName:   mockvcf.DomainName,
				ClusterNames: []string{mockvcf.ClusterName},
				Logs:         []string{"sddcManagerLogs", "esxLogs"},
				Force:        ptr(false),
			},
			want: `{"logs":{"esxLogs":true,"sddcManagerLogs":true},` +
				`"options":{"config":{"force":false}},` +
				`"scope":{"domains":[{"clusterNames":["sfo-w01-cl01"],"domainName":"sfo-w01"}]}}`,
			why: "force was set to false and must be sent; the other 14 Logs members and options.include were unset and must not be",
		},
		{
			name: "free hosts, an include item and skipKnownHostCheck=false",
			req: sddcdiag.DiagnoseRequest{
				ResourceID:         mockvcf.ClusterResourceID,
				DomainName:         mockvcf.DomainName,
				Logs:               []string{"nsxLogs"},
				IncludeFreeHosts:   ptr(true),
				SkipKnownHostCheck: ptr(false),
				HealthCheck:        ptr(true),
			},
			want: `{"logs":{"nsxLogs":true},` +
				`"options":{"config":{"skipKnownHostCheck":false},"include":{"healthCheck":true}},` +
				`"scope":{"domains":[{"domainName":"sfo-w01"}],"includeFreeHosts":true}}`,
			why: "options.config carries only skipKnownHostCheck and options.include only healthCheck",
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			srv := mockvcf.Start(t)
			c := newClient(t, srv)

			if _, err := c.Diagnose(context.Background(), tc.req); err != nil {
				t.Fatalf("Diagnose: %v", err)
			}

			reqs := srv.RequestsFor("startSupportBundle")
			if len(reqs) != 1 {
				t.Fatalf("startSupportBundle was called %d times, want 1", len(reqs))
			}
			got := canonical(t, reqs[0].Body)
			if got != tc.want {
				t.Errorf("SupportBundleSpec body mismatch (%s)\n got: %s\nwant: %s", tc.why, got, tc.want)
			}
		})
	}
}

func TestStartSupportBundleCompactsEmptyObjectsAndPreservesExplicitFalse(t *testing.T) {
	cases := []struct {
		name string
		spec sddcdiag.SupportBundleSpec
		want string
	}{
		{
			name: "empty optional objects are absent, including an empty domain entry",
			spec: sddcdiag.SupportBundleSpec{
				Logs: &sddcdiag.Logs{},
				Options: &sddcdiag.SupportBundleOption{
					Config:  &sddcdiag.SupportBundleConfig{},
					Include: &sddcdiag.SupportBundleIncludeItems{},
				},
				Scope: &sddcdiag.SupportBundleScope{Domains: []sddcdiag.Domains{{}}},
			},
			want: `{}`,
		},
		{
			name: "false values survive while their unset siblings stay absent",
			spec: sddcdiag.SupportBundleSpec{
				Logs: &sddcdiag.Logs{ESXLogs: ptr(false)},
				Options: &sddcdiag.SupportBundleOption{
					Config:  &sddcdiag.SupportBundleConfig{Force: ptr(false)},
					Include: &sddcdiag.SupportBundleIncludeItems{SummaryReport: ptr(false)},
				},
				Scope: &sddcdiag.SupportBundleScope{
					IncludeFreeHosts: ptr(false),
					Domains: []sddcdiag.Domains{{
						DomainName:   mockvcf.DomainName,
						ClusterNames: []string{},
					}},
				},
			},
			want: `{"logs":{"esxLogs":false},` +
				`"options":{"config":{"force":false},"include":{"summaryReport":false}},` +
				`"scope":{"domains":[{"domainName":"sfo-w01"}],"includeFreeHosts":false}}`,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			srv := mockvcf.Start(t)
			c := newClient(t, srv)
			if _, err := c.StartSupportBundle(context.Background(), tc.spec); err != nil {
				t.Fatalf("StartSupportBundle: %v", err)
			}
			reqs := srv.RequestsFor("startSupportBundle")
			if len(reqs) != 1 {
				t.Fatalf("startSupportBundle was called %d times, want 1", len(reqs))
			}
			if got := canonical(t, reqs[0].Body); got != tc.want {
				t.Errorf("SupportBundleSpec body\n got: %s\nwant: %s", got, tc.want)
			}
		})
	}
}

func TestDiagnoseRejectsALogNameOutsideTheContract(t *testing.T) {
	srv := mockvcf.Start(t)
	c := newClient(t, srv)
	_, err := c.Diagnose(context.Background(), sddcdiag.DiagnoseRequest{
		ResourceID: mockvcf.ClusterResourceID,
		DomainName: mockvcf.DomainName,
		Logs:       []string{"hcxLogs"},
	})
	if err == nil || !strings.Contains(err.Error(), "hcxLogs") {
		t.Fatalf("Diagnose error = %v, want rejection naming hcxLogs", err)
	}
	if got := len(srv.RequestsFor("startSupportBundle")); got != 0 {
		t.Errorf("invalid Logs name was silently dropped and startSupportBundle was called %d times", got)
	}
}

// ---------------------------------------------------------------------------
// Diagnose: request sequence, headers, and the diagnosis itself
// ---------------------------------------------------------------------------

func diagnoseOnce(t *testing.T) (*mockvcf.Server, *sddcdiag.Diagnosis) {
	t.Helper()
	srv := mockvcf.Start(t)
	c := newClient(t, srv)
	d, err := c.Diagnose(context.Background(), sddcdiag.DiagnoseRequest{
		ResourceID:   mockvcf.ClusterResourceID,
		DomainName:   mockvcf.DomainName,
		ClusterNames: []string{mockvcf.ClusterName},
		Logs:         []string{"sddcManagerLogs", "esxLogs"},
		Force:        ptr(false),
	})
	if err != nil {
		t.Fatalf("Diagnose: %v", err)
	}
	if d == nil {
		t.Fatal("Diagnose returned a nil diagnosis and a nil error")
	}
	return srv, d
}

func TestDiagnoseCallsExactlyTheContractOperationsInOrder(t *testing.T) {
	srv, _ := diagnoseOnce(t)

	want := []string{
		"getTasks",
		"getTask",
		"getNotifications",
		"startSupportBundle",
		"getSupportBundleStatus", // IN_PROGRESS
		"getSupportBundleStatus", // COMPLETED_WITH_SUCCESS
		"exportSupportBundleByID",
	}
	if got := srv.OperationSequence(); !reflect.DeepEqual(got, want) {
		t.Errorf("operation sequence\n got: %v\nwant: %v", got, want)
	}

	for i, r := range srv.Requests() {
		if r.OperationID == "" {
			t.Errorf("request %d went to %s %s, which docs/contract.json does not name", i, r.Method, r.Path)
		}
		if r.Status >= 400 {
			t.Errorf("request %d (%s) was answered %d", i, r.OperationID, r.Status)
		}
	}
}

func TestDiagnoseStopsAndFailsWhenBundleCollectionFails(t *testing.T) {
	srv := mockvcf.StartWithTerminalStatus(t, "COMPLETED_WITH_FAILURE")
	c := newClient(t, srv)
	_, err := c.Diagnose(context.Background(), sddcdiag.DiagnoseRequest{
		ResourceID: mockvcf.ClusterResourceID,
		DomainName: mockvcf.DomainName,
	})
	if err == nil || !strings.Contains(err.Error(), "COMPLETED_WITH_FAILURE") {
		t.Fatalf("Diagnose error = %v, want terminal collection failure", err)
	}
	want := []string{
		"getTasks", "getTask", "getNotifications", "startSupportBundle",
		"getSupportBundleStatus", "getSupportBundleStatus",
	}
	if got := srv.OperationSequence(); !reflect.DeepEqual(got, want) {
		t.Errorf("operation sequence after terminal failure\n got: %v\nwant: %v", got, want)
	}
	if got := len(srv.RequestsFor("exportSupportBundleByID")); got != 0 {
		t.Errorf("bundle export was attempted %d times after collection failure", got)
	}
}

func TestDiagnoseQueriesTasksWithOnlyTheFiveParametersItNeeds(t *testing.T) {
	srv, _ := diagnoseOnce(t)

	reqs := srv.RequestsFor("getTasks")
	if len(reqs) != 1 {
		t.Fatalf("getTasks was called %d times, want 1", len(reqs))
	}
	want := map[string]string{
		"taskStatus":     "FAILED",
		"resourceId":     mockvcf.ClusterResourceID,
		"orderBy":        "creationTimestamp",
		"orderDirection": "DESC",
		"pageSize":       "1",
	}
	got := reqs[0].Query
	if len(got) != len(want) {
		t.Errorf("Diagnose sent %d task parameters, want %d (?%s)", len(got), len(want), reqs[0].RawQuery)
	}
	for k, v := range want {
		if vals := got[k]; len(vals) != 1 || vals[0] != v {
			t.Errorf("task parameter %s = %v, want [%s]", k, vals, v)
		}
	}
}

func TestEveryRequestCarriesTheBearerTokenAndTheOperationsOwnMediaTypes(t *testing.T) {
	srv, _ := diagnoseOnce(t)

	wantAccept := map[string]string{
		"getTasks":                "application/json",
		"getTask":                 "application/json",
		"getNotifications":        "application/json",
		"startSupportBundle":      "application/json",
		"getSupportBundleStatus":  "application/json",
		"exportSupportBundleByID": "application/octet-stream",
	}

	for i, r := range srv.Requests() {
		if r.Authorization != "Bearer "+mockvcf.Token {
			t.Errorf("request %d (%s): Authorization = %q, want %q", i, r.OperationID, r.Authorization, "Bearer "+mockvcf.Token)
		}
		if got := wantAccept[r.OperationID]; !strings.Contains(r.Accept, got) {
			t.Errorf("request %d (%s): Accept = %q, want it to offer %q", i, r.OperationID, r.Accept, got)
		}
		if r.OperationID == "startSupportBundle" {
			if !strings.Contains(r.ContentType, "application/json") {
				t.Errorf("startSupportBundle: Content-Type = %q, want application/json", r.ContentType)
			}
			continue
		}
		if r.ContentType != "" {
			t.Errorf("request %d (%s): sent Content-Type %q on a request with no body", i, r.OperationID, r.ContentType)
		}
		if len(r.Body) != 0 {
			t.Errorf("request %d (%s): sent a %d byte body on a GET", i, r.OperationID, len(r.Body))
		}
	}
}

func TestDiagnoseReportsTheNestedRootCauseRatherThanTheTopLevelSummary(t *testing.T) {
	_, d := diagnoseOnce(t)

	if d.TaskID != mockvcf.FailedTaskID {
		t.Errorf("TaskID = %q, want the newest failed task %q", d.TaskID, mockvcf.FailedTaskID)
	}
	if d.TaskStatus != "FAILED" {
		t.Errorf("TaskStatus = %q, want FAILED", d.TaskStatus)
	}
	if want := "Add hosts to cluster " + mockvcf.ClusterName; d.TaskName != want {
		t.Errorf("TaskName = %q, want %q", d.TaskName, want)
	}

	wantSubs := []string{"Add hosts to vSphere cluster", "Rollback partial cluster expansion"}
	if !reflect.DeepEqual(d.FailedSubTasks, wantSubs) {
		t.Errorf("FailedSubTasks = %v, want %v", d.FailedSubTasks, wantSubs)
	}

	const summary = "Cluster expansion failed. Inspect the sub-tasks for details."
	if d.RootCause == summary {
		t.Fatal("RootCause is the task's own top-level summary; the reason is nested two levels below the failed sub-task")
	}
	const wantCause = "ESXi host esx-04.sfo.rainpole.io cannot reach any of its configured NTP servers " +
		"(ntp0.sfo.rainpole.io, ntp1.sfo.rainpole.io)."
	if d.RootCause != wantCause {
		t.Errorf("RootCause\n got: %q\nwant: %q", d.RootCause, wantCause)
	}

	wantTokens := []string{"A1B2C3", "RVK7QW", "P8M2ZD", "LX4T9B", "RB55CN"}
	if !reflect.DeepEqual(d.ReferenceTokens, wantTokens) {
		t.Errorf("ReferenceTokens = %v, want depth-first %v", d.ReferenceTokens, wantTokens)
	}
}

func TestDiagnoseKeepsOnlyTheNotificationsRaisedOnTheAffectedResource(t *testing.T) {
	_, d := diagnoseOnce(t)

	want := []string{
		"ERROR: Cluster sfo-w01-cl01 expansion failed; one host was left outside the cluster.",
		"WARNING: Time synchronisation drift detected on esx-04.sfo.rainpole.io.",
	}
	if !reflect.DeepEqual(d.Notifications, want) {
		t.Errorf("Notifications\n got: %v\nwant: %v", d.Notifications, want)
	}
}

func TestDiagnoseDownloadsTheBundleAndCorrelatesItsLinesByReferenceToken(t *testing.T) {
	_, d := diagnoseOnce(t)

	if d.BundleID != mockvcf.BundleID {
		t.Errorf("BundleID = %q, want %q", d.BundleID, mockvcf.BundleID)
	}

	sum := sha256.Sum256(mockvcf.BundleBytes())
	if want := hex.EncodeToString(sum[:]); d.BundleSHA256 != want {
		t.Errorf("BundleSHA256 = %q, want the digest of the bytes the mock served, %q", d.BundleSHA256, want)
	}

	// Derived from the bundle text rather than restated, so the expectation and
	// the fixture cannot drift apart. File order, not reference-token order.
	tokens := map[string]bool{
		"A1B2C3": true, "RVK7QW": true, "P8M2ZD": true, "LX4T9B": true, "RB55CN": true,
	}
	var want []string
	for _, line := range strings.Split(strings.TrimRight(mockvcf.BundleLog(), "\n"), "\n") {
		for tok := range tokens {
			if strings.Contains(line, "[ref="+tok+"]") {
				want = append(want, line)
				break
			}
		}
	}
	if len(want) != 5 {
		t.Fatalf("fixture drift: derived %d evidence lines, want 5", len(want))
	}
	if !reflect.DeepEqual(d.Evidence, want) {
		t.Errorf("Evidence\n got: %v\nwant: %v", d.Evidence, want)
	}
	for _, line := range d.Evidence {
		if strings.Contains(line, "[ref=ZZ0000]") {
			t.Error("Evidence includes the line tagged ZZ0000, which belongs to an unrelated task")
		}
	}
}

// ---------------------------------------------------------------------------
// The package ships its own table-driven tests
// ---------------------------------------------------------------------------

func TestSddcdiagShipsTableDrivenTests(t *testing.T) {
	dir := filepath.Join(repoRoot(t), "sddcdiag")
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read sddcdiag/: %v", err)
	}
	var files []string
	for _, e := range entries {
		if !e.IsDir() && strings.HasSuffix(e.Name(), "_test.go") {
			files = append(files, filepath.Join(dir, e.Name()))
		}
	}
	sort.Strings(files)
	if len(files) == 0 {
		t.Fatal("sddcdiag/ ships no _test.go file")
	}

	fset := token.NewFileSet()
	testFuncs, tableDriven := 0, 0
	for _, f := range files {
		file, err := parser.ParseFile(fset, f, nil, 0)
		if err != nil {
			t.Fatalf("parse %s: %v", f, err)
		}
		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv != nil || !strings.HasPrefix(fn.Name.Name, "Test") {
				continue
			}
			testFuncs++
			hasTable, hasRange := false, false
			ast.Inspect(fn.Body, func(n ast.Node) bool {
				switch v := n.(type) {
				case *ast.CompositeLit:
					// A []struct{...}{...} literal: the case table.
					if at, ok := v.Type.(*ast.ArrayType); ok && at.Len == nil {
						if _, ok := at.Elt.(*ast.StructType); ok {
							hasTable = true
						}
					}
				case *ast.RangeStmt:
					hasRange = true
				}
				return true
			})
			if hasTable && hasRange {
				tableDriven++
			}
		}
	}

	if testFuncs < 3 {
		t.Errorf("sddcdiag/ declares %d test functions, want at least 3", testFuncs)
	}
	if tableDriven < 3 {
		t.Errorf("sddcdiag/ declares %d Test functions that contain both a []struct{...} case table and a range loop, want at least 3", tableDriven)
	}
}

func TestSddcdiagUsesOnlyTheStandardLibrary(t *testing.T) {
	root := repoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, "go.mod"))
	if err != nil {
		t.Fatalf("read go.mod: %v", err)
	}
	for _, line := range strings.Split(string(raw), "\n") {
		if s := strings.TrimSpace(line); strings.HasPrefix(s, "require") {
			t.Errorf("go.mod declares a dependency (%q); this package must build against the standard library alone", s)
		}
	}
	if _, err := os.Stat(filepath.Join(root, "vendor")); err == nil {
		t.Error("a vendor/ directory was added; this package must build against the standard library alone")
	}
}
