// Command cataloggen renders the small catalog HTTP client from api/catalog.json.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"regexp"
)

type schema struct {
	Package   string    `json:"package"`
	Operation operation `json:"operation"`
}

type operation struct {
	Name       string      `json:"name"`
	Method     string      `json:"method"`
	Path       string      `json:"path"`
	Parameters []parameter `json:"parameters"`
}

type parameter struct {
	GoName   string `json:"goName"`
	WireName string `json:"wireName"`
	Type     string `json:"type"`
}

var (
	identifier = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9]*$`)
	wireName   = regexp.MustCompile(`^[a-z][a-z0-9_]*$`)
)

func main() {
	schemaPath := flag.String("schema", "", "path to the catalog schema")
	outPath := flag.String("out", "", "path to write the generated Go client")
	flag.Parse()

	if *schemaPath == "" || *outPath == "" || flag.NArg() != 0 {
		fmt.Fprintln(os.Stderr, "usage: cataloggen -schema PATH -out PATH")
		os.Exit(2)
	}

	raw, err := os.ReadFile(*schemaPath)
	if err != nil {
		fatal(err)
	}
	var spec schema
	if err := json.Unmarshal(raw, &spec); err != nil {
		fatal(fmt.Errorf("decode schema: %w", err))
	}
	if err := validate(spec); err != nil {
		fatal(err)
	}

	generated, err := render(spec)
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*outPath, generated, 0o644); err != nil {
		fatal(err)
	}
}

func validate(spec schema) error {
	if !identifier.MatchString(spec.Package) {
		return errors.New("schema package is not a Go identifier")
	}
	if spec.Operation.Name != "ListWidgets" {
		return fmt.Errorf("unsupported operation %q", spec.Operation.Name)
	}
	if spec.Operation.Method != "GET" {
		return fmt.Errorf("unsupported method %q", spec.Operation.Method)
	}
	if spec.Operation.Path == "" || spec.Operation.Path[0] != '/' {
		return errors.New("operation path must be absolute")
	}
	seenGo := make(map[string]bool)
	seenWire := make(map[string]bool)
	for _, p := range spec.Operation.Parameters {
		if !identifier.MatchString(p.GoName) {
			return fmt.Errorf("parameter Go name %q is invalid", p.GoName)
		}
		if !wireName.MatchString(p.WireName) {
			return fmt.Errorf("parameter wire name %q is invalid", p.WireName)
		}
		if seenGo[p.GoName] || seenWire[p.WireName] {
			return fmt.Errorf("duplicate parameter %q/%q", p.GoName, p.WireName)
		}
		seenGo[p.GoName] = true
		seenWire[p.WireName] = true
		switch p.Type {
		case "string", "int", "bool":
		default:
			return fmt.Errorf("parameter %q has unsupported type %q", p.GoName, p.Type)
		}
	}
	return nil
}

func render(spec schema) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by cataloggen; DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "//go:generate go run ../../cmd/cataloggen -schema ../../api/catalog.json -out client.gen.go\n\n")
	fmt.Fprintf(&b, "package %s\n\n", spec.Package)
	fmt.Fprintln(&b, "import (")
	fmt.Fprintln(&b, `	"context"`)
	fmt.Fprintln(&b, `	"encoding/json"`)
	fmt.Fprintln(&b, `	"fmt"`)
	fmt.Fprintln(&b, `	"net/http"`)
	fmt.Fprintln(&b, `	"net/url"`)
	fmt.Fprintln(&b, `	"strconv"`)
	fmt.Fprintln(&b, `	"strings"`)
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type Widget struct {")
	fmt.Fprintln(&b, "\tID string `json:\"id\"`")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "type %sOptions struct {\n", spec.Operation.Name)
	for _, p := range spec.Operation.Parameters {
		switch p.Type {
		case "string":
			fmt.Fprintf(&b, "\t%s string\n", p.GoName)
		case "int":
			fmt.Fprintf(&b, "\t%s int\n", p.GoName)
		case "bool":
			fmt.Fprintf(&b, "\t%s *bool\n", p.GoName)
		}
	}
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "type %sResponse struct {\n", spec.Operation.Name)
	fmt.Fprintln(&b, "\tWidgets []Widget `json:\"widgets\"`")
	fmt.Fprintln(&b, "\tNextPageToken string `json:\"next_page_token\"`")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "type Client struct {")
	fmt.Fprintln(&b, "\tbaseURL *url.URL")
	fmt.Fprintln(&b, "\thttpClient *http.Client")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func NewClient(rawBaseURL string, httpClient *http.Client) (*Client, error) {")
	fmt.Fprintln(&b, "\tbaseURL, err := url.Parse(rawBaseURL)")
	fmt.Fprintln(&b, "\tif err != nil {")
	fmt.Fprintln(&b, "\t\treturn nil, fmt.Errorf(\"parse catalog base URL: %w\", err)")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\tif baseURL.Scheme == \"\" || baseURL.Host == \"\" {")
	fmt.Fprintln(&b, "\t\treturn nil, fmt.Errorf(\"catalog base URL must be absolute\")")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\tif httpClient == nil {")
	fmt.Fprintln(&b, "\t\thttpClient = http.DefaultClient")
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\treturn &Client{baseURL: baseURL, httpClient: httpClient}, nil")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "func (c *Client) %s(ctx context.Context, opts %sOptions) (%sResponse, error) {\n", spec.Operation.Name, spec.Operation.Name, spec.Operation.Name)
	fmt.Fprintln(&b, "\tu := *c.baseURL")
	fmt.Fprintf(&b, "\tu.Path = strings.TrimRight(u.Path, \"/\") + %q\n", spec.Operation.Path)
	fmt.Fprintln(&b, "\tq := u.Query()")
	for _, p := range spec.Operation.Parameters {
		switch p.Type {
		case "string":
			fmt.Fprintf(&b, "\tif opts.%s != \"\" {\n", p.GoName)
			fmt.Fprintf(&b, "\t\tq.Set(%q, opts.%s)\n", p.WireName, p.GoName)
			fmt.Fprintln(&b, "\t}")
		case "int":
			fmt.Fprintf(&b, "\tif opts.%s != 0 {\n", p.GoName)
			fmt.Fprintf(&b, "\t\tq.Set(%q, strconv.Itoa(opts.%s))\n", p.WireName, p.GoName)
			fmt.Fprintln(&b, "\t}")
		case "bool":
			fmt.Fprintf(&b, "\tif opts.%s != nil {\n", p.GoName)
			fmt.Fprintf(&b, "\t\tq.Set(%q, strconv.FormatBool(*opts.%s))\n", p.WireName, p.GoName)
			fmt.Fprintln(&b, "\t}")
		}
	}
	fmt.Fprintln(&b, "\tu.RawQuery = q.Encode()")
	fmt.Fprintf(&b, "\treq, err := http.NewRequestWithContext(ctx, %q, u.String(), nil)\n", spec.Operation.Method)
	fmt.Fprintln(&b, "\tif err != nil {")
	fmt.Fprintf(&b, "\t\treturn %sResponse{}, fmt.Errorf(\"build catalog request: %%w\", err)\n", spec.Operation.Name)
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\tres, err := c.httpClient.Do(req)")
	fmt.Fprintln(&b, "\tif err != nil {")
	fmt.Fprintf(&b, "\t\treturn %sResponse{}, fmt.Errorf(\"list widgets: %%w\", err)\n", spec.Operation.Name)
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\tdefer res.Body.Close()")
	fmt.Fprintln(&b, "\tif res.StatusCode != http.StatusOK {")
	fmt.Fprintf(&b, "\t\treturn %sResponse{}, fmt.Errorf(\"list widgets: unexpected HTTP status %%d\", res.StatusCode)\n", spec.Operation.Name)
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintf(&b, "\tvar decoded %sResponse\n", spec.Operation.Name)
	fmt.Fprintln(&b, "\tif err := json.NewDecoder(res.Body).Decode(&decoded); err != nil {")
	fmt.Fprintf(&b, "\t\treturn %sResponse{}, fmt.Errorf(\"decode list widgets response: %%w\", err)\n", spec.Operation.Name)
	fmt.Fprintln(&b, "\t}")
	fmt.Fprintln(&b, "\treturn decoded, nil")
	fmt.Fprintln(&b, "}")

	return format.Source(b.Bytes())
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, err)
	os.Exit(1)
}
