#!/usr/bin/env bash

set -u

if [[ ${1-} != -Pk || ${2-} != -- || $# -ne 3 ]]; then
  printf 'unexpected df invocation\n' >&2
  exit 64
fi

printf 'Filesystem 1024-blocks Used Available Capacity Mounted on\n'
printf 'fixture    100000      1    %s        1%%       /fixture\n' \
  "${READINESS_TEST_AVAILABLE_KB:?READINESS_TEST_AVAILABLE_KB is required}"
