<#
    Protected verification driver.

    Exercises the public surface of src/VCFOpsNetworks against the loopback
    fixture and writes what the module reported to -OutFile as JSON.  The
    verifier then checks both the reported result and the request log the
    fixture recorded.

    Do not edit this file to make a test pass.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)] [string] $ModulePath,
    [Parameter(Mandatory)] [string] $Scenario,
    [Parameter(Mandatory)] [string] $ServerHost,
    [Parameter(Mandatory)] [int]    $Port,
    [Parameter(Mandatory)] [string] $OutFile
)

$ErrorActionPreference = 'Stop'
$WarningPreference = 'SilentlyContinue'

$report = [ordered]@{
    scenario          = $Scenario
    connect_error     = $null
    rollout_error     = $null
    disconnect_error  = $null
    rollout           = $null
    import_error      = $null
}

function Save-Report {
    $json = $report | ConvertTo-Json -Depth 20
    Set-Content -LiteralPath $OutFile -Value $json -Encoding utf8
}

try {
    Import-Module $ModulePath -Force -ErrorAction Stop
}
catch {
    $report.import_error = $_.Exception.Message
    Save-Report
    exit 2
}

$password = ConvertTo-SecureString 'P@ssw0rd-Fixture' -AsPlainText -Force
$credential = [pscredential]::new('svc-netops@lab.local', $password)

$common = @{
    Server               = $ServerHost
    Port                 = $Port
    Protocol             = 'http'
    SkipCertificateCheck = $true
}

$connection = $null
try {
    switch ($Scenario) {
        'rollout-failure' { $connection = Connect-VCFOpsNetworksServer @common -Credential $credential }
        'bearer-success'  { $connection = Connect-VCFOpsNetworksServer @common -OpsAccessToken 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.fixture.ops-jwt' }
        'application-failure' { $connection = Connect-VCFOpsNetworksServer @common -OpsAccessToken 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.fixture.ops-jwt' }
        'auth-failure'    { $connection = Connect-VCFOpsNetworksServer @common -Credential $credential }
        'domain-local'    { $connection = Connect-VCFOpsNetworksServer @common -Credential $credential -DomainType 'LOCAL' }
        'domain-ldap'     { $connection = Connect-VCFOpsNetworksServer @common -Credential $credential -DomainType 'LDAP' -DomainValue 'corp.example.com' }
        default           { throw "unknown scenario '$Scenario'" }
    }
}
catch {
    $report.connect_error = $_.Exception.Message
    Save-Report
    exit 3
}

$tiers = $null
switch ($Scenario) {
    'rollout-failure' {
        $tiers = @(
            @{ Name = 'web'; SearchFilter = "security_groups.entity_id = '18230:82:604573173'" },
            @{ Name = 'app'; IpAddresses = @('10.10.20.0/24', '10.10.21.5-10.10.21.40') },
            @{ Name = 'db';  SearchFilter = "vm_tag = 'payments-db'"; SourceGroupEntityId = @('18230:566:264351372') },
            @{ Name = 'must-not-run'; SearchFilter = "name = 'later-tier'" }
        )
    }
    'bearer-success' {
        $tiers = @(
            @{
                Name = 'combined'
                SearchFilter = "name = 'café-vm'"
                IpAddresses = @('10.20.30.40')
                SourceGroupEntityId = @()
            },
            @{ Name = 'standalone' }
        )
    }
    'application-failure' {
        $tiers = @(
            @{ Name = 'must-not-run' }
        )
    }
}

if ($null -ne $tiers) {
    try {
        $result = New-VCFOpsNetworksApplication -Connection $connection -Name 'Payments-Prod' -Tier $tiers
        $report.rollout = $result
    }
    catch {
        $report.rollout_error = $_.Exception.Message
    }
}

try {
    Disconnect-VCFOpsNetworksServer -Connection $connection
}
catch {
    $report.disconnect_error = $_.Exception.Message
}

Save-Report
exit 0
