#!/usr/bin/env python3
"""Protected verification for the VCFOpsNetworks module.

Starts the contract-pinned loopback fixture, drives the module through it with
tests/driver.ps1, then asserts (a) the exact wire shape of every request the
module produced and (b) that the module reported the outcome of the multi-step
rollout accurately.

No live VMware endpoint is contacted: every request goes to 127.0.0.1.

Do not edit this file to make a test pass.
"""

import json
import os
import re
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTRACT = os.path.join(ROOT, "docs", "contract.json")
MOCK = os.path.join(ROOT, "mock", "ni_mock.py")
DRIVER = os.path.join(ROOT, "tests", "driver.ps1")
MODULE_DIR = os.path.join(ROOT, "src", "VCFOpsNetworks")
MANIFEST = os.path.join(MODULE_DIR, "VCFOpsNetworks.psd1")

BASE = "/api/ni"
APP_ID = "18230:561:100000001"
TOKEN = "NetworkInsight ni-session-token-0001"
OPS_JWT = "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.fixture.ops-jwt"
USERNAME = "svc-netops@lab.local"
PASSWORD = "P@ssw0rd-Fixture"
FAIL_MESSAGE = "Tier membership criteria could not be resolved against the current inventory."
APP_FAIL_MESSAGE = "An application with this name already exists."
AUTH_FAIL_MESSAGE = "The supplied credentials are invalid."

failures = []
checks = [0]


def check(label, condition, detail=""):
    checks[0] += 1
    if condition:
        print("  PASS  %s" % label)
    else:
        print("  FAIL  %s" % label)
        if detail:
            for line in str(detail).splitlines():
                print("        %s" % line)
        failures.append(label)


def check_equal(label, actual, expected):
    ok = actual == expected
    detail = ""
    if not ok:
        detail = "expected: %s\nactual:   %s" % (
            json.dumps(expected, sort_keys=True, default=str),
            json.dumps(actual, sort_keys=True, default=str),
        )
    check(label, ok, detail)


def as_list(value):
    """PowerShell's ConvertTo-Json collapses single-element arrays to objects."""
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


# ---------------------------------------------------------------------------
# Fixture lifecycle
# ---------------------------------------------------------------------------


class Fixture:
    def __init__(self, log_path, fail_tier=None, fail_operation=None, fail_status=400,
                 fail_message=FAIL_MESSAGE):
        self.log_path = log_path
        cmd = [sys.executable, MOCK, "--contract", CONTRACT, "--log", log_path, "--port", "0"]
        if fail_tier:
            cmd += ["--fail-tier", fail_tier]
        if fail_operation:
            cmd += ["--fail-operation", fail_operation]
        if fail_tier or fail_operation:
            cmd += ["--fail-status", str(fail_status), "--fail-message", fail_message]
        self.proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        line = self.proc.stdout.readline()
        m = re.match(r"PORT (\d+)", line or "")
        if not m:
            self.proc.kill()
            raise RuntimeError("fixture did not start: %r %s" % (line, self.proc.stderr.read()))
        self.port = int(m.group(1))
        self._await_ready()

    def _await_ready(self):
        deadline = time.time() + 10
        url = "http://127.0.0.1:%d%s/__ready" % (self.port, BASE)
        while time.time() < deadline:
            try:
                urllib.request.urlopen(url, timeout=1)
                return
            except urllib.error.HTTPError:
                return  # a 404 from the contract router means it is serving
            except OSError:
                time.sleep(0.05)
        raise RuntimeError("fixture never became ready")

    def requests(self):
        entries = []
        with open(self.log_path, encoding="utf-8") as fh:
            for line in fh:
                if line.strip():
                    entries.append(json.loads(line))
        # drop the readiness probe
        return [e for e in entries if not e["path"].endswith("/__ready")]

    def stop(self):
        self.proc.terminate()
        try:
            self.proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            self.proc.kill()


def run_scenario(scenario, fail_tier=None, fail_operation=None, fail_status=400,
                 fail_message=FAIL_MESSAGE):
    with tempfile.TemporaryDirectory(prefix="vcfon-%s-" % scenario) as workdir:
        log_path = os.path.join(workdir, "requests.jsonl")
        out_path = os.path.join(workdir, "result.json")
        fixture = Fixture(log_path, fail_tier, fail_operation, fail_status, fail_message)
        try:
            proc = subprocess.run(
                [
                    "pwsh", "-NoProfile", "-NonInteractive", "-File", DRIVER,
                    "-ModulePath", MANIFEST,
                    "-Scenario", scenario,
                    "-ServerHost", "127.0.0.1",
                    "-Port", str(fixture.port),
                    "-OutFile", out_path,
                ],
                capture_output=True, text=True, timeout=300,
            )
            requests = fixture.requests()
        finally:
            fixture.stop()

        report = None
        if os.path.exists(out_path):
            with open(out_path, encoding="utf-8") as fh:
                report = json.load(fh)
        return proc, requests, report


def summarise(requests):
    return [(r["method"], r["path"]) for r in requests]


# ---------------------------------------------------------------------------
# Static checks on the module itself
# ---------------------------------------------------------------------------


def check_module_wiring():
    print("\n[1] module packaging")

    probe = (
        "$ErrorActionPreference='Stop'; $WarningPreference='SilentlyContinue';"
        "Import-Module '%s' -Force -ErrorAction Stop;"
        "[pscustomobject]@{"
        " exported = @((Get-Command -Module VCFOpsNetworks).Name | Sort-Object) }"
        " | ConvertTo-Json -Depth 6"
    ) % MANIFEST

    proc = subprocess.run(
        ["pwsh", "-NoProfile", "-NonInteractive", "-Command", probe],
        capture_output=True, text=True, timeout=300,
    )
    try:
        info = json.loads(proc.stdout)
    except ValueError:
        check("module imports cleanly", False, proc.stdout + "\n" + proc.stderr)
        return

    vendored = []
    for dirpath, _dirnames, filenames in os.walk(MODULE_DIR):
        for name in filenames:
            if name.lower().startswith("vmware.sdk.vcf") or name.lower().endswith(".dll"):
                vendored.append(os.path.join(dirpath, name))
    check("no DLLs or copied SDK files under src/VCFOpsNetworks", not vendored, "\n".join(vendored))

    check_equal(
        "module exports exactly the three contracted functions",
        as_list(info.get("exported")),
        ["Connect-VCFOpsNetworksServer", "Disconnect-VCFOpsNetworksServer", "New-VCFOpsNetworksApplication"],
    )


# ---------------------------------------------------------------------------
# Scenario 1: multi-step rollout where the third tier fails
# ---------------------------------------------------------------------------


def check_rollout_failure():
    print("\n[2] native session auth, three-tier rollout, third tier rejected")
    proc, requests, report = run_scenario("rollout-failure", fail_tier="db")

    if report is None:
        check("driver produced a report", False, proc.stdout + "\n" + proc.stderr)
        return
    check("module imported without error", report.get("import_error") is None, report.get("import_error"))
    check("Connect-VCFOpsNetworksServer succeeded", report.get("connect_error") is None, report.get("connect_error"))

    # -- wire shape ---------------------------------------------------------
    expected_calls = [
        ("POST", BASE + "/auth/token"),
        ("POST", BASE + "/groups/applications"),
        ("POST", BASE + "/groups/applications/%s/tiers" % APP_ID),
        ("POST", BASE + "/groups/applications/%s/tiers" % APP_ID),
        ("POST", BASE + "/groups/applications/%s/tiers" % APP_ID),
        ("GET", BASE + "/groups/applications/%s/tiers" % APP_ID),
        ("DELETE", BASE + "/auth/token"),
    ]
    check_equal("exact sequence of API calls", summarise(requests), expected_calls)
    if len(requests) != len(expected_calls):
        return

    auth, app, web, tier_app, db, listing, logout = requests

    check_equal(
        "operationId 'create' body omits the unset optional 'domain'",
        auth["body_json"],
        {"username": USERNAME, "password": PASSWORD},
    )
    check(
        "operationId 'create' is sent unauthenticated",
        "authorization" not in auth["headers"],
        auth["headers"],
    )
    check_equal(
        "operationId 'create' declares Content-Type application/json",
        (auth["headers"].get("content-type") or "").split(";")[0].strip(),
        "application/json",
    )

    check_equal(
        "operationId 'addApplication' body carries only 'name'",
        app["body_json"],
        {"name": "Payments-Prod"},
    )
    check_equal(
        "session token is presented as the ApiKeyAuth scheme",
        app["headers"].get("authorization"),
        TOKEN,
    )

    check_equal(
        "tier 'web' sends only a SearchMembershipCriteria; member_list and source_group_entity_id omitted",
        web["body_json"],
        {
            "name": "web",
            "group_membership_criteria": [
                {
                    "membership_type": "SearchMembershipCriteria",
                    "search_membership_criteria": {
                        "entity_type": "VirtualMachine",
                        "filter": "security_groups.entity_id = '18230:82:604573173'",
                    },
                }
            ],
        },
    )
    check_equal(
        "tier 'app' sends only an IPAddressMembershipCriteria",
        tier_app["body_json"],
        {
            "name": "app",
            "group_membership_criteria": [
                {
                    "membership_type": "IPAddressMembershipCriteria",
                    "ip_address_membership_criteria": {
                        "ip_addresses": ["10.10.20.0/24", "10.10.21.5-10.10.21.40"]
                    },
                }
            ],
        },
    )
    check_equal(
        "tier 'db' sends source_group_entity_id because it was set",
        db["body_json"],
        {
            "name": "db",
            "group_membership_criteria": [
                {
                    "membership_type": "SearchMembershipCriteria",
                    "search_membership_criteria": {
                        "entity_type": "VirtualMachine",
                        "filter": "vm_tag = 'payments-db'",
                    },
                }
            ],
            "source_group_entity_id": ["18230:566:264351372"],
        },
    )
    check("operationId 'listApplicationTiers' sends no body", listing["body_raw"] == "", listing["body_raw"])
    check("operationId 'delete' sends no body", logout["body_raw"] == "", logout["body_raw"])
    check_equal("operationId 'delete' presents the session token", logout["headers"].get("authorization"), TOKEN)

    # -- reporting accuracy -------------------------------------------------
    check(
        "an API rejection is reported, not thrown as a terminating error",
        report.get("rollout_error") is None,
        report.get("rollout_error"),
    )
    rollout = report.get("rollout")
    if not isinstance(rollout, dict):
        check("New-VCFOpsNetworksApplication returned a result object", False, rollout)
        return

    check_equal("rollout Status", rollout.get("Status"), "Failed")
    check_equal("rollout ApplicationName", rollout.get("ApplicationName"), "Payments-Prod")
    check_equal("rollout ApplicationEntityId", rollout.get("ApplicationEntityId"), APP_ID)

    steps = [
        {
            "Index": s.get("Index"),
            "Operation": s.get("Operation"),
            "Target": s.get("Target"),
            "Status": s.get("Status"),
            "EntityId": s.get("EntityId"),
        }
        for s in as_list(rollout.get("Steps"))
    ]
    check_equal(
        "every attempted step is reported with its true outcome, and no step after the failure",
        steps,
        [
            {
                "Index": 1, "Operation": "addApplication", "Target": "Payments-Prod",
                "Status": "Succeeded", "EntityId": APP_ID,
            },
            {
                "Index": 2, "Operation": "addTier", "Target": "web",
                "Status": "Succeeded", "EntityId": "18230:562:200000001",
            },
            {
                "Index": 3, "Operation": "addTier", "Target": "app",
                "Status": "Succeeded", "EntityId": "18230:562:200000002",
            },
            {
                "Index": 4, "Operation": "addTier", "Target": "db",
                "Status": "Failed", "EntityId": None,
            },
        ],
    )

    failed = rollout.get("FailedStep")
    if isinstance(failed, dict):
        check_equal("FailedStep operation", failed.get("Operation"), "addTier")
        check_equal("FailedStep target", failed.get("Target"), "db")
        check_equal("FailedStep status code", failed.get("StatusCode"), 400)
        check(
            "FailedStep carries the appliance's own error message",
            FAIL_MESSAGE in str(failed.get("Message")),
            failed.get("Message"),
        )
    else:
        check("FailedStep describes the rejected step", False, failed)

    created = [
        {"Name": t.get("Name"), "EntityId": t.get("EntityId")}
        for t in as_list(rollout.get("CreatedTiers"))
    ]
    check_equal(
        "CreatedTiers reflects the tiers confirmed to exist server-side",
        created,
        [
            {"Name": "web", "EntityId": "18230:562:200000001"},
            {"Name": "app", "EntityId": "18230:562:200000002"},
        ],
    )
    check(
        "the partially applied change was left in place, not rolled back",
        not any(r["method"] == "DELETE" and "/groups/" in r["path"] for r in requests),
        summarise(requests),
    )
    check("Disconnect-VCFOpsNetworksServer succeeded", report.get("disconnect_error") is None, report.get("disconnect_error"))


# ---------------------------------------------------------------------------
# Scenario 2: VCF Operations JWT auth, rollout succeeds
# ---------------------------------------------------------------------------


def check_bearer_success():
    print("\n[3] VCF Operations JWT auth and successful wire-shape variants")
    proc, requests, report = run_scenario("bearer-success")

    if report is None:
        check("driver produced a report", False, proc.stdout + "\n" + proc.stderr)
        return
    check("Connect-VCFOpsNetworksServer succeeded", report.get("connect_error") is None, report.get("connect_error"))

    check_equal(
        "no session is created or revoked when an Ops JWT is supplied",
        summarise(requests),
        [
            ("POST", BASE + "/groups/applications"),
            ("POST", BASE + "/groups/applications/%s/tiers" % APP_ID),
            ("POST", BASE + "/groups/applications/%s/tiers" % APP_ID),
            ("GET", BASE + "/groups/applications/%s/tiers" % APP_ID),
        ],
    )
    if len(requests) != 4:
        return

    app, combined, standalone, _listing = requests
    check_equal("Ops JWT is presented as the OpsTokenAuth scheme", app["headers"].get("authorization"), OPS_JWT)
    check_equal(
        "both criteria are sent in the required order and an empty optional source list is omitted",
        combined["body_json"],
        {
            "name": "combined",
            "group_membership_criteria": [
                {
                    "membership_type": "SearchMembershipCriteria",
                    "search_membership_criteria": {
                        "entity_type": "VirtualMachine",
                        "filter": "name = 'café-vm'",
                    },
                },
                {
                    "membership_type": "IPAddressMembershipCriteria",
                    "ip_address_membership_criteria": {
                        "ip_addresses": ["10.20.30.40"],
                    },
                },
            ],
        },
    )
    check_equal(
        "a tier with no optional fields sends only 'name'",
        standalone["body_json"],
        {"name": "standalone"},
    )

    rollout = report.get("rollout")
    if not isinstance(rollout, dict):
        check("New-VCFOpsNetworksApplication returned a result object", False, rollout)
        return
    check_equal("rollout Status", rollout.get("Status"), "Succeeded")
    check("FailedStep is empty on success", rollout.get("FailedStep") in (None, ""), rollout.get("FailedStep"))
    check_equal(
        "CreatedTiers on success",
        [{"Name": t.get("Name"), "EntityId": t.get("EntityId")} for t in as_list(rollout.get("CreatedTiers"))],
        [
            {"Name": "combined", "EntityId": "18230:562:200000001"},
            {"Name": "standalone", "EntityId": "18230:562:200000002"},
        ],
    )
    check_equal(
        "steps reported on success",
        [
            (s.get("Index"), s.get("Operation"), s.get("Target"), s.get("Status"), s.get("EntityId"))
            for s in as_list(rollout.get("Steps"))
        ],
        [
            (1, "addApplication", "Payments-Prod", "Succeeded", APP_ID),
            (2, "addTier", "combined", "Succeeded", "18230:562:200000001"),
            (3, "addTier", "standalone", "Succeeded", "18230:562:200000002"),
        ],
    )
    check("Disconnect-VCFOpsNetworksServer succeeded", report.get("disconnect_error") is None, report.get("disconnect_error"))


# ---------------------------------------------------------------------------
# Scenario 3: application creation is rejected
# ---------------------------------------------------------------------------


def check_application_failure():
    print("\n[4] application rejection is reported and no listing is attempted")
    proc, requests, report = run_scenario(
        "application-failure",
        fail_operation="addApplication",
        fail_status=409,
        fail_message=APP_FAIL_MESSAGE,
    )

    if report is None:
        check("driver produced a report", False, proc.stdout + "\n" + proc.stderr)
        return
    check("Connect-VCFOpsNetworksServer succeeded", report.get("connect_error") is None, report.get("connect_error"))
    check_equal(
        "only addApplication is attempted",
        summarise(requests),
        [("POST", BASE + "/groups/applications")],
    )
    check(
        "the application rejection is returned rather than thrown",
        report.get("rollout_error") is None,
        report.get("rollout_error"),
    )
    rollout = report.get("rollout")
    if not isinstance(rollout, dict):
        check("New-VCFOpsNetworksApplication returned a result object", False, rollout)
        return
    check_equal("failed application rollout Status", rollout.get("Status"), "Failed")
    check_equal("failed application rollout ApplicationName", rollout.get("ApplicationName"), "Payments-Prod")
    check_equal("failed application rollout ApplicationEntityId", rollout.get("ApplicationEntityId"), None)
    check_equal("no tiers can be confirmed when application creation fails", as_list(rollout.get("CreatedTiers")), [])
    check_equal(
        "only the failed addApplication step is reported",
        [
            {
                "Index": s.get("Index"), "Operation": s.get("Operation"),
                "Target": s.get("Target"), "Status": s.get("Status"),
                "EntityId": s.get("EntityId"),
            }
            for s in as_list(rollout.get("Steps"))
        ],
        [
            {
                "Index": 1, "Operation": "addApplication", "Target": "Payments-Prod",
                "Status": "Failed", "EntityId": None,
            }
        ],
    )
    failed = rollout.get("FailedStep")
    check_equal("failed application operation", (failed or {}).get("Operation"), "addApplication")
    check_equal("failed application target", (failed or {}).get("Target"), "Payments-Prod")
    check_equal("failed application status code", (failed or {}).get("StatusCode"), 409)
    check_equal("failed application appliance message", (failed or {}).get("Message"), APP_FAIL_MESSAGE)


# ---------------------------------------------------------------------------
# Scenario 4: authentication failure remains terminating
# ---------------------------------------------------------------------------


def check_auth_failure():
    print("\n[5] native authentication rejection is terminating")
    proc, requests, report = run_scenario(
        "auth-failure",
        fail_operation="create",
        fail_status=401,
        fail_message=AUTH_FAIL_MESSAGE,
    )

    if report is None:
        check("driver produced a report", False, proc.stdout + "\n" + proc.stderr)
        return
    check_equal("only native session creation is attempted", summarise(requests), [("POST", BASE + "/auth/token")])
    check(
        "authentication failure terminates Connect-VCFOpsNetworksServer",
        AUTH_FAIL_MESSAGE in str(report.get("connect_error")) and "401" in str(report.get("connect_error")),
        report.get("connect_error"),
    )
    check_equal("no rollout result follows failed authentication", report.get("rollout"), None)


# ---------------------------------------------------------------------------
# Scenarios 5 and 6: nested optional omission on UserCredential.domain
# ---------------------------------------------------------------------------


def check_domain(scenario, label, expected_domain):
    print("\n%s" % label)
    proc, requests, report = run_scenario(scenario)

    if report is None:
        check("driver produced a report", False, proc.stdout + "\n" + proc.stderr)
        return
    check("Connect-VCFOpsNetworksServer succeeded", report.get("connect_error") is None, report.get("connect_error"))
    check_equal(
        "calls made",
        summarise(requests),
        [("POST", BASE + "/auth/token"), ("DELETE", BASE + "/auth/token")],
    )
    if not requests:
        return
    check_equal(
        "credential body",
        requests[0]["body_json"],
        {"username": USERNAME, "password": PASSWORD, "domain": expected_domain},
    )


# ---------------------------------------------------------------------------


def main():
    for path in (CONTRACT, MOCK, DRIVER, MANIFEST):
        if not os.path.exists(path):
            print("missing required file: %s" % path)
            return 1

    check_module_wiring()
    check_rollout_failure()
    check_bearer_success()
    check_application_failure()
    check_auth_failure()
    check_domain(
        "domain-local",
        "[6] LOCAL domain: 'value' is omitted because it was not supplied",
        {"domain_type": "LOCAL"},
    )
    check_domain(
        "domain-ldap",
        "[7] LDAP domain: both domain fields are supplied and sent",
        {"domain_type": "LDAP", "value": "corp.example.com"},
    )

    print("\n%d checks, %d failed" % (checks[0], len(failures)))
    if failures:
        print("\nfailed checks:")
        for name in failures:
            print("  - %s" % name)
        return 1
    print("OK")
    return 0


if __name__ == "__main__":
    sys.exit(main())
