#!/usr/bin/env bash

set -u

if [[ -e $CHANGE_WORK_DIR/fail-step-30 ]]; then
  printf 'fixture step 30 failed\n' >&2
  exit 43
fi

printf 'gamma\n' >"$CHANGE_WORK_DIR/gamma"
printf '30-write-gamma\n' >>"$CHANGE_WORK_DIR/mutations.log"
