// Code generated by cataloggen; DO NOT EDIT.

//go:generate go run ../../cmd/cataloggen -schema ../../api/catalog.json -out client.gen.go

package catalogapi

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"
)

type Widget struct {
	ID string `json:"id"`
}

type ListWidgetsOptions struct {
	PageSize       int
	PageToken      string
	IncludeRetired *bool
}

type ListWidgetsResponse struct {
	Widgets       []Widget `json:"widgets"`
	NextPageToken string   `json:"next_page_token"`
}

type Client struct {
	baseURL    *url.URL
	httpClient *http.Client
}

func NewClient(rawBaseURL string, httpClient *http.Client) (*Client, error) {
	baseURL, err := url.Parse(rawBaseURL)
	if err != nil {
		return nil, fmt.Errorf("parse catalog base URL: %w", err)
	}
	if baseURL.Scheme == "" || baseURL.Host == "" {
		return nil, fmt.Errorf("catalog base URL must be absolute")
	}
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &Client{baseURL: baseURL, httpClient: httpClient}, nil
}

func (c *Client) ListWidgets(ctx context.Context, opts ListWidgetsOptions) (ListWidgetsResponse, error) {
	u := *c.baseURL
	u.Path = strings.TrimRight(u.Path, "/") + "/v1/widgets"
	q := u.Query()
	if opts.PageSize != 0 {
		q.Set("page_size", strconv.Itoa(opts.PageSize))
	}
	if opts.PageToken != "" {
		q.Set("cursor", opts.PageToken)
	}
	if opts.IncludeRetired != nil {
		q.Set("include_retired", strconv.FormatBool(*opts.IncludeRetired))
	}
	u.RawQuery = q.Encode()
	req, err := http.NewRequestWithContext(ctx, "GET", u.String(), nil)
	if err != nil {
		return ListWidgetsResponse{}, fmt.Errorf("build catalog request: %w", err)
	}
	res, err := c.httpClient.Do(req)
	if err != nil {
		return ListWidgetsResponse{}, fmt.Errorf("list widgets: %w", err)
	}
	defer res.Body.Close()
	if res.StatusCode != http.StatusOK {
		return ListWidgetsResponse{}, fmt.Errorf("list widgets: unexpected HTTP status %d", res.StatusCode)
	}
	var decoded ListWidgetsResponse
	if err := json.NewDecoder(res.Body).Decode(&decoded); err != nil {
		return ListWidgetsResponse{}, fmt.Errorf("decode list widgets response: %w", err)
	}
	return decoded, nil
}
