"""Protected verifier for the VCF Automation batch deployment client.

Runs the real client as a subprocess against the loopback mock appliance, then
asserts the exact wire shape of every request it made by reading the mock's
request log. No live VMware endpoint is contacted: the mock binds 127.0.0.1 on an
ephemeral port and the client is pointed at that address.

Do not edit this file, mock/, or docs/ to make these tests pass.
"""

import base64
import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "mock"))

from vcfa_mock import MockAppliance  # noqa: E402

TERMINAL = {"SUCCESSFUL", "FAILED", "ABORTED", "APPROVAL_REJECTED"}

# Optional fields of the token form body that this run never sets. None may be
# emitted, not even with an empty value.
TOKEN_OPTIONAL_UNSET = [
    "code",
    "redirect_uri",
    "scope",
    "org_id",
    "subject_token",
    "subject_token_type",
    "code_verifier",
    "client_id",
]

# deploymentName -> exact set of keys the create body must carry, given
# inputs/batch.json. Anything else present, or any of these missing, is a
# wire-shape violation.
EXPECTED_CREATE_KEYS = {
    "web-01": {"deploymentName", "projectId", "inputs"},
    "web-02": {"deploymentName", "projectId", "inputs", "reason"},
    "db-01": {"deploymentName", "projectId", "inputs", "version"},
}

EXPECTED_TERMINAL_STATUS = {
    "web-01": "SUCCESSFUL",
    "web-02": "SUCCESSFUL",
    "db-01": "FAILED",
}

RESULT_KEYS = {
    "deploymentName",
    "deploymentId",
    "requestId",
    "status",
    "completedTasks",
    "totalTasks",
}


class WireContractTest(unittest.TestCase):
    """One client run, many assertions over its request log."""

    @classmethod
    def setUpClass(cls):
        cls._tmp = tempfile.TemporaryDirectory()
        tmp = Path(cls._tmp.name)
        cls.log_path = tmp / "requests.jsonl"
        cls.out_path = tmp / "results.json"
        config_path = tmp / "config.json"

        cls.appliance = MockAppliance(log_path=cls.log_path)
        base_url = cls.appliance.start()
        fixtures = cls.appliance.fixtures

        config_path.write_text(
            json.dumps(
                {
                    "baseUrl": base_url,
                    "clientId": fixtures["client"]["client_id"],
                    "clientSecret": fixtures["client"]["client_secret"],
                    "refreshToken": fixtures["refresh_token"],
                    "projectId": fixtures["project_id"],
                }
            )
        )

        env = dict(os.environ)
        env["PYTHONPATH"] = str(REPO_ROOT / "src")
        try:
            cls.proc = subprocess.run(
                [sys.executable, "-S", "-m", "vcfa_client",
                 "--config", str(config_path),
                 "--batch", str(REPO_ROOT / "inputs" / "batch.json"),
                 "--out", str(cls.out_path)],
                cwd=str(REPO_ROOT),
                env=env,
                capture_output=True,
                text=True,
                timeout=120,
            )
        finally:
            cls.appliance.stop()

        cls.entries = cls.appliance.entries()
        cls.batch = json.loads((REPO_ROOT / "inputs" / "batch.json").read_text())
        cls.results = None
        if cls.out_path.exists():
            try:
                cls.results = json.loads(cls.out_path.read_text())
            except ValueError:
                cls.results = None

    @classmethod
    def tearDownClass(cls):
        cls._tmp.cleanup()

    # -- helpers --------------------------------------------------------

    def ops(self, operation_id):
        return [e for e in self.entries if e["operation_id"] == operation_id]

    def creates_by_name(self):
        out = {}
        for entry in self.ops("requestCatalogItem"):
            body = entry.get("body_json") or {}
            out.setdefault(body.get("deploymentName"), []).append(entry)
        return out

    def result_for(self, name):
        for item in (self.results or {}).get("deployments", []):
            if item.get("deploymentName") == name:
                return item
        return None

    # -- process --------------------------------------------------------

    def test_client_run_succeeded(self):
        self.assertEqual(
            self.proc.returncode, 0,
            "client exited %d\nstdout:\n%s\nstderr:\n%s"
            % (self.proc.returncode, self.proc.stdout, self.proc.stderr),
        )

    def test_results_file_written(self):
        self.assertIsNotNone(self.results, "no parseable results JSON was written")
        self.assertEqual(
            set(self.results), {"deployments"},
            "results JSON must contain exactly the documented deployments envelope",
        )
        self.assertIsInstance(self.results["deployments"], list)

    # -- contract surface -----------------------------------------------

    def test_only_contract_operations_were_called(self):
        stray = [
            "%s %s" % (e["method"], e["path"])
            for e in self.entries
            if not e["matched_contract_operation"]
        ]
        self.assertEqual(
            stray, [],
            "client called operations the contract does not name: %s" % stray,
        )

    def test_catalog_items_were_resolved_over_the_api(self):
        self.assertGreaterEqual(
            len(self.ops("listCatalogItems")), 1,
            "catalog item ids must be resolved by name via GET /catalog/api/items",
        )

    def test_no_api_version_negotiation(self):
        for entry in self.entries:
            names = [k for k, _ in entry["query_pairs"]]
            self.assertNotIn(
                "apiVersion", names,
                "seq %d sent an apiVersion parameter; the contract documents none"
                % entry["seq"],
            )
            accept = entry["headers"].get("accept") or ""
            self.assertNotIn(
                "version=", accept,
                "seq %d sent a versioned media type (%r); not documented for this service"
                % (entry["seq"], accept),
            )

    def test_no_query_parameters_are_sent_for_this_run(self):
        for entry in self.entries:
            self.assertEqual(
                entry["query_pairs"], [],
                "seq %d sent query parameters %s, but this run sets none; all "
                "optional parameters must be omitted"
                % (entry["seq"], entry["query_pairs"]),
            )

    def test_get_operations_have_no_request_body(self):
        for entry in self.entries:
            if entry["method"] == "GET":
                self.assertEqual(
                    entry["body_raw"], "",
                    "seq %d sent a request body on GET %s"
                    % (entry["seq"], entry["path"]),
                )

    # -- token operation wire shape -------------------------------------

    def test_access_token_issued_exactly_twice(self):
        calls = self.ops("issueAccessToken")
        self.assertEqual(
            len(calls), 2,
            "expected exactly 2 token calls (one at start, one after the token "
            "expired), got %d. Refresh lazily on 401, not per request." % len(calls),
        )

    def test_token_request_uses_basic_client_authentication(self):
        fixtures = self.appliance.fixtures
        raw = "%s:%s" % (fixtures["client"]["client_id"], fixtures["client"]["client_secret"])
        expected = "Basic " + base64.b64encode(raw.encode()).decode()
        for entry in self.ops("issueAccessToken"):
            self.assertEqual(
                entry["headers"]["authorization"], expected,
                "seq %d: token operation requires Authorization: "
                "Basic base64(client_id:client_secret)" % entry["seq"],
            )
            ctype = (entry["headers"]["content-type"] or "").split(";")[0].strip()
            self.assertEqual(
                ctype, "application/x-www-form-urlencoded",
                "seq %d: token body must be form encoded" % entry["seq"],
            )

    def test_token_request_body_is_exactly_the_refresh_grant(self):
        for entry in self.ops("issueAccessToken"):
            pairs = entry["form_pairs"] or []
            names = [k for k, _ in pairs]
            self.assertEqual(
                sorted(names), ["grant_type", "refresh_token"],
                "seq %d: token form body must carry exactly grant_type and "
                "refresh_token, got %s" % (entry["seq"], names),
            )
            form = dict(pairs)
            self.assertEqual(form["grant_type"], "refresh_token")
            self.assertEqual(form["refresh_token"], self.appliance.fixtures["refresh_token"])

    def test_token_request_omits_unset_optional_fields(self):
        for entry in self.ops("issueAccessToken"):
            names = [k for k, _ in (entry["form_pairs"] or [])]
            for field in TOKEN_OPTIONAL_UNSET:
                self.assertNotIn(
                    field, names,
                    "seq %d: optional form field %r is not set for this run and "
                    "must be omitted entirely, not sent empty" % (entry["seq"], field),
                )
            blank = [k for k, v in (entry["form_pairs"] or []) if v == ""]
            self.assertEqual(
                blank, [],
                "seq %d: form fields %s were sent with empty values" % (entry["seq"], blank),
            )

    def test_protected_operations_use_bearer_scheme(self):
        for entry in self.entries:
            if entry["operation_id"] == "issueAccessToken":
                continue
            auth = entry["headers"]["authorization"] or ""
            self.assertTrue(
                auth.startswith("Bearer "),
                "seq %d (%s) must authenticate with Authorization: Bearer <JWT>, got %r"
                % (entry["seq"], entry["operation_id"], auth[:16]),
            )

    # -- expiry and recovery --------------------------------------------

    def test_token_expiry_occurred_exactly_once(self):
        expired = [e for e in self.entries if e.get("auth_failure") == "expired_token"]
        self.assertEqual(
            len(expired), 1,
            "expected the access token to expire exactly once mid-run, saw %d "
            "expiry rejections" % len(expired),
        )

    def test_no_request_used_a_revoked_or_unknown_token(self):
        bad = [
            (e["seq"], e["auth_failure"]) for e in self.entries
            if e.get("auth_failure") in ("revoked_token", "unknown_token")
        ]
        self.assertEqual(
            bad, [],
            "requests were sent with a superseded or unknown access token: %s" % bad,
        )

    def test_rejected_request_was_retried_with_the_new_token(self):
        expired = [e for e in self.entries if e.get("auth_failure") == "expired_token"]
        self.assertEqual(len(expired), 1)
        failed = expired[0]
        stale_token_id = failed["auth_token_id"]

        refreshes = [
            e for e in self.ops("issueAccessToken")
            if e["seq"] > failed["seq"] and e["status"] == 200
        ]
        self.assertTrue(
            refreshes,
            "no access token was issued after the 401; the run abandoned the "
            "expired token instead of refreshing it",
        )
        refresh = refreshes[0]

        retries = [
            e for e in self.entries
            if e["seq"] > refresh["seq"]
            and e["operation_id"] == failed["operation_id"]
            and e["path"] == failed["path"]
            and e["status"] == 200
        ]
        self.assertTrue(
            retries,
            "the request rejected at seq %d (%s %s) was never retried after "
            "re-authenticating; that work was lost"
            % (failed["seq"], failed["method"], failed["path"]),
        )
        self.assertNotEqual(
            retries[0]["auth_token_id"], stale_token_id,
            "the retry reused the expired access token",
        )

        after = [
            e["seq"] for e in self.entries
            if e["seq"] > refresh["seq"] and e["auth_token_id"] == stale_token_id
        ]
        self.assertEqual(
            after, [],
            "requests at seq %s still carried the expired access token after the "
            "refresh" % after,
        )

    # -- no lost or duplicated work -------------------------------------

    def test_each_deployment_submitted_exactly_once(self):
        expected = sorted(r["deploymentName"] for r in self.batch["requests"])
        creates = self.creates_by_name()
        self.assertEqual(
            sorted(creates), expected,
            "the set of submitted deployments does not match the batch",
        )
        for name, entries in creates.items():
            self.assertEqual(
                len(entries), 1,
                "deployment %r was submitted %d times. Re-authenticating must not "
                "resubmit work that already succeeded." % (name, len(entries)),
            )

    def test_create_targets_the_resolved_catalog_item(self):
        by_name = {item["name"]: item["id"] for item in self.appliance.fixtures["catalog_items"]}
        wanted = {r["deploymentName"]: r["catalogItemName"] for r in self.batch["requests"]}
        for name, entries in self.creates_by_name().items():
            expected_id = by_name[wanted[name]]
            self.assertEqual(
                entries[0]["path_params"].get("id"), expected_id,
                "deployment %r was requested against the wrong catalog item id" % name,
            )

    def test_polling_neither_restarted_nor_overran(self):
        scripts = self.appliance.fixtures["request_scripts"]
        polls = {}
        for entry in self.ops("getRequest"):
            request_id = entry["path_params"]["requestId"]
            polls[request_id] = polls.get(request_id, 0) + (1 if entry["status"] == 200 else 0)

        for deployment_id, request_id in self.appliance.state.by_deployment.items():
            name = self.appliance.state.deployments[deployment_id]["name"]
            expected = len(scripts["by_deployment_name"].get(name, scripts["default"]))
            self.assertEqual(
                polls.get(request_id, 0), expected,
                "deployment %r was polled %d times but reaches a terminal state on "
                "poll %d. Fewer means it was never followed to completion; more "
                "means polling restarted after re-authenticating instead of "
                "resuming." % (name, polls.get(request_id, 0), expected),
            )

    # -- create body wire shape -----------------------------------------

    def test_create_body_carries_exactly_the_fields_the_input_sets(self):
        for name, entries in self.creates_by_name().items():
            body = entries[0]["body_json"]
            self.assertIsInstance(
                body, dict,
                "deployment %r was not sent as a JSON object body" % name,
            )
            self.assertEqual(
                set(body), EXPECTED_CREATE_KEYS[name],
                "deployment %r sent body keys %s but the batch entry sets %s. "
                "Optional fields the input does not set must be omitted."
                % (name, sorted(body), sorted(EXPECTED_CREATE_KEYS[name])),
            )

    def test_create_body_never_sends_empty_placeholders(self):
        for name, entries in self.creates_by_name().items():
            body = entries[0]["body_json"] or {}
            for key, value in body.items():
                self.assertIsNotNone(
                    value,
                    "deployment %r sent %r as null; omit the field instead" % (name, key),
                )
                self.assertNotEqual(
                    value, "",
                    "deployment %r sent %r as an empty string; omit the field instead"
                    % (name, key),
                )

    def test_create_body_never_sends_bulk_request_count(self):
        for name, entries in self.creates_by_name().items():
            self.assertNotIn(
                "bulkRequestCount", entries[0]["body_json"] or {},
                "deployment %r sent bulkRequestCount; this run never sets it" % name,
            )

    def test_create_body_values_match_the_batch(self):
        specs = {r["deploymentName"]: r for r in self.batch["requests"]}
        project_id = self.appliance.fixtures["project_id"]
        for name, entries in self.creates_by_name().items():
            body = entries[0]["body_json"]
            spec = specs[name]
            self.assertEqual(body["deploymentName"], name)
            self.assertEqual(body["projectId"], project_id)
            self.assertEqual(body["inputs"], spec["inputs"])
            if "reason" in spec:
                self.assertEqual(body["reason"], spec["reason"])
            if "version" in spec:
                self.assertEqual(body["version"], spec["version"])

    # -- results ---------------------------------------------------------

    def test_every_deployment_reported_with_its_terminal_state(self):
        self.assertIsNotNone(self.results)
        reported = {item.get("deploymentName") for item in self.results["deployments"]}
        self.assertEqual(
            reported, set(EXPECTED_TERMINAL_STATUS),
            "results must report every batch entry exactly once",
        )
        self.assertEqual(
            len(self.results["deployments"]), len(EXPECTED_TERMINAL_STATUS),
            "results contain duplicate entries",
        )
        for name, status in EXPECTED_TERMINAL_STATUS.items():
            item = self.result_for(name)
            self.assertEqual(
                set(item), RESULT_KEYS,
                "deployment %r result must contain exactly the documented fields"
                % name,
            )
            self.assertEqual(
                item.get("status"), status,
                "deployment %r should end %s, results say %r"
                % (name, status, item.get("status")),
            )
            self.assertIn(item.get("status"), TERMINAL)

    def test_reported_ids_match_what_the_appliance_issued(self):
        self.assertIsNotNone(self.results)
        issued = {
            record["name"]: (deployment_id, self.appliance.state.by_deployment[deployment_id])
            for deployment_id, record in self.appliance.state.deployments.items()
        }
        for name in EXPECTED_TERMINAL_STATUS:
            item = self.result_for(name)
            deployment_id, request_id = issued[name]
            self.assertEqual(
                item.get("deploymentId"), deployment_id,
                "deployment %r reports a deploymentId the appliance never issued" % name,
            )
            self.assertEqual(
                item.get("requestId"), request_id,
                "deployment %r reports a requestId the appliance never issued" % name,
            )

    def test_reported_progress_is_the_final_task_count(self):
        for name in EXPECTED_TERMINAL_STATUS:
            item = self.result_for(name)
            scripts = self.appliance.fixtures["request_scripts"]
            total = len(scripts["by_deployment_name"].get(name, scripts["default"]))
            self.assertEqual(
                item.get("totalTasks"), total,
                "deployment %r reports totalTasks %r, expected %d"
                % (name, item.get("totalTasks"), total),
            )
            self.assertEqual(
                item.get("completedTasks"), total,
                "deployment %r reports completedTasks %r, expected %d"
                % (name, item.get("completedTasks"), total),
            )


if __name__ == "__main__":
    unittest.main()
