#!/usr/bin/env python3
"""Derive docs/contract.json from the pinned VCF Operations OpenAPI document.

The contract is generated from the specification itself -- never from a
documentation page. Re-run to reproduce docs/contract.json byte for byte:

    curl -sSL -o /tmp/vcf-operations-openapi.json \
      https://raw.githubusercontent.com/vmware/vcf-api-specs/<COMMIT>/<SPEC_PATH>
    python3 tools/derive_contract.py /tmp/vcf-operations-openapi.json \
      docs/contract.json

The verifier does NOT run this script and never touches the network.
"""
import hashlib
import json
import sys

COMMIT = "c3f3b52c845dd967cabbc21680e893292077d5ba"
SPEC_PATH = "specifications/vcf-operations/vcf-operations-openapi.json"
REPO = "https://github.com/vmware/vcf-api-specs"

# The exact operationIds this task's client is permitted to use, in the order
# a correct rotation performs them. Every entry is asserted against the spec.
OPERATIONS = [
    ("acquireToken", "post", "/api/auth/token/acquire"),
    ("getCurrentVersionOfServer", "get", "/api/versions/current"),
    ("getCredentials", "get", "/api/credentials"),
    ("createCredential", "post", "/api/credentials"),
    ("enumerateAdapterInstances", "get", "/api/adapters"),
    ("patchAdapterInstance", "patch", "/api/adapters"),
    ("partialUpdateCredential", "patch", "/api/credentials"),
    ("releaseToken", "post", "/api/auth/token/release"),
]

# Schemas whose required/optional split the wire-shape verifier asserts against.
SCHEMAS = ["username-password", "credential", "name-value",
           "adapter-instance", "resource-key"]


def split_props(schema):
    required = sorted(schema.get("required", []))
    props = sorted(schema.get("properties", {}).keys())
    return required, [p for p in props if p not in required]


def ref_name(node):
    if isinstance(node, dict) and "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    return None


def main():
    spec_file, out_file = sys.argv[1], sys.argv[2]
    with open(spec_file, "rb") as fh:
        raw = fh.read()
    spec = json.loads(raw)
    schemas = spec["components"]["schemas"]

    sec_name, sec = next(iter(spec["components"]["securitySchemes"].items()))

    operations = {}
    for op_id, method, path in OPERATIONS:
        node = spec["paths"][path][method]
        assert node["operationId"] == op_id, (path, method, node["operationId"])

        entry = {
            "operationId": op_id,
            "method": method.upper(),
            "path": path,
            "summary": node.get("summary"),
        }

        params = []
        for p in node.get("parameters", []):
            params.append({
                "name": p["name"],
                "in": p["in"],
                "required": bool(p.get("required", False)),
                "type": p.get("schema", {}).get("type"),
            })
        if params:
            entry["parameters"] = params

        body = node.get("requestBody")
        if body:
            schema_name = ref_name(body["content"]["application/json"]["schema"])
            entry["requestBody"] = {
                "required": bool(body.get("required", False)),
                "schema": schema_name,
            }

        ok = next((c for c in ("200", "201", "204") if c in node["responses"]), None)
        entry["successStatus"] = int(ok)
        content = node["responses"][ok].get("content") or {}
        if "application/json" in content:
            entry["responseSchema"] = ref_name(content["application/json"]["schema"])
        operations[op_id] = entry

    model = {}
    for name in SCHEMAS:
        required, optional = split_props(schemas[name])
        model[name] = {"required": required, "optional": optional}

    contract = {
        "$comment": (
            "Generated by tools/derive_contract.py from the VCF Operations "
            "OpenAPI specification. Do not hand-edit."
        ),
        "source": {
            "repository": REPO,
            "specPath": SPEC_PATH,
            "commit": COMMIT,
            "specSha256": hashlib.sha256(raw).hexdigest(),
            "openapi": spec["openapi"],
            "apiTitle": spec["info"]["title"],
            "apiVersion": spec["info"]["version"],
        },
        "basePath": spec["servers"][0]["url"],
        "security": {
            "schemeName": sec_name,
            "type": sec["type"],
            "in": sec["in"],
            "headerName": sec["name"],
        },
        "operations": operations,
        "schemas": model,
    }

    with open(out_file, "w") as fh:
        json.dump(contract, fh, indent=2, sort_keys=False)
        fh.write("\n")
    print("wrote %s (%d operations)" % (out_file, len(operations)))


if __name__ == "__main__":
    main()
