#!/usr/bin/env bash
set -euo pipefail

usage() {
    printf 'usage: %s {diagnose|fix|verify} SNAPSHOT [EXPORTS_FILE]\n' "${0##*/}" >&2
    exit 64
}

[[ $# -ge 2 && $# -le 3 ]] || usage
command_name=$1
snapshot=$2
exports_file=${3:-"$snapshot/exports"}

[[ -r "$snapshot/server.conf" && -r "$snapshot/clients.tsv" ]] || {
    printf 'snapshot is missing server.conf or clients.tsv: %s\n' "$snapshot" >&2
    exit 66
}
[[ -r "$exports_file" ]] || {
    printf 'cannot read exports file: %s\n' "$exports_file" >&2
    exit 66
}

# The snapshot is generated by our collector and contains assignments only.
# shellcheck disable=SC1090
source "$snapshot/server.conf"
: "${share:?missing share in server.conf}"
: "${owner_uid:?missing owner_uid in server.conf}"
: "${owner_gid:?missing owner_gid in server.conf}"
: "${mode:?missing mode in server.conf}"

export_has_client() {
    local wanted=$1 line rest spec host

    while IFS= read -r line || [[ -n $line ]]; do
        [[ $line == "$share "* || $line == "$share"$'\t'* ]] || continue
        rest=${line#"$share"}
        read -r -a specs <<< "$rest"
        for spec in "${specs[@]}"; do
            host=${spec%%(*}
            [[ $host == "$wanted" ]] && return 0
        done
    done < "$exports_file"
    return 1
}

mount_is_writable_nfs4() {
    local options=",$1,"
    [[ $options == *,rw,* && $options == *,vers=4.*,* ]]
}

filesystem_is_writable() {
    local uid=$1 gid=$2 numeric_mode permission_bit
    numeric_mode=$((8#${mode#0}))

    if [[ $uid == "$owner_uid" ]]; then
        permission_bit=$((8#200))
    elif [[ $gid == "$owner_gid" ]]; then
        permission_bit=$((8#020))
    else
        permission_bit=$((8#002))
    fi
    (( (numeric_mode & permission_bit) != 0 ))
}

client_status() {
    local name=$1 address=$2 network=$3 uid=$4 gid=$5 mount_options=$6
    local network_status=bad identity_status=bad mount_status=bad
    local export_status=missing filesystem_status=denied access_status=denied

    [[ $network == ok ]] && network_status=ok
    [[ $uid == "$owner_uid" && $gid == "$owner_gid" ]] && identity_status=ok
    mount_is_writable_nfs4 "$mount_options" && mount_status=ok
    export_has_client "$address" && export_status=ok
    filesystem_is_writable "$uid" "$gid" && filesystem_status=ok

    if [[ $network_status == ok && $identity_status == ok && $mount_status == ok &&
          $export_status == ok && $filesystem_status == ok ]]; then
        access_status=ok
    fi

    printf 'client=%s address=%s network=%s identity=%s mount=%s export=%s filesystem=%s access=%s\n' \
        "$name" "$address" "$network_status" "$identity_status" "$mount_status" \
        "$export_status" "$filesystem_status" "$access_status"
    [[ $access_status == ok ]]
}

diagnose_all() {
    local failures=0 name address network uid gid mount_options
    while IFS=$'\t' read -r name address network uid gid mount_options; do
        [[ -n $name && $name != \#* ]] || continue
        client_status "$name" "$address" "$network" "$uid" "$gid" "$mount_options" || failures=$((failures + 1))
    done < "$snapshot/clients.tsv"
    (( failures == 0 ))
}

missing_export_is_only_fault() {
    local address=$1 network=$2 uid=$3 gid=$4 mount_options=$5
    [[ $network == ok ]] &&
        [[ $uid == "$owner_uid" && $gid == "$owner_gid" ]] &&
        mount_is_writable_nfs4 "$mount_options" &&
        filesystem_is_writable "$uid" "$gid" &&
        ! export_has_client "$address"
}

add_explicit_client() {
    local address=$1 tmp line rest first_spec options client_spec found=0
    tmp="${exports_file}.nfsexport-doctor.$$"
    : > "$tmp"

    # Build the client selector from the address recorded by the collector.
    client_spec="${address%.*}.*"

    while IFS= read -r line || [[ -n $line ]]; do
        if [[ $line == "$share "* || $line == "$share"$'\t'* ]]; then
            rest=${line#"$share"}
            read -r first_spec _ <<< "$rest"
            if [[ $first_spec =~ \(([^()]*)\)$ ]]; then
                options=${BASH_REMATCH[1]}
            else
                rm -f "$tmp"
                printf 'cannot determine options for export %s\n' "$share" >&2
                return 65
            fi
            printf '%s %s(%s)\n' "$line" "$client_spec" "$options" >> "$tmp"
            found=1
        else
            printf '%s\n' "$line" >> "$tmp"
        fi
    done < "$exports_file"

    if (( found == 0 )); then
        rm -f "$tmp"
        printf 'share is not present in exports: %s\n' "$share" >&2
        return 65
    fi
    mv "$tmp" "$exports_file"
}

fix_exports() {
    local changed=0 name address network uid gid mount_options
    while IFS=$'\t' read -r name address network uid gid mount_options; do
        [[ -n $name && $name != \#* ]] || continue
        if missing_export_is_only_fault "$address" "$network" "$uid" "$gid" "$mount_options"; then
            add_explicit_client "$address"
            printf 'fix: added %s for %s\n' "$address" "$name"
            changed=$((changed + 1))
        fi
    done < "$snapshot/clients.tsv"

    if (( changed == 0 )); then
        printf 'fix: no export-only fault found; unchanged\n' >&2
        return 1
    fi
    verify_all
}

verify_all() {
    local failures=0 name address network uid gid mount_options
    while IFS=$'\t' read -r name address network uid gid mount_options; do
        [[ -n $name && $name != \#* ]] || continue
        if client_status "$name" "$address" "$network" "$uid" "$gid" "$mount_options" >/dev/null; then
            printf 'verify: %s ok\n' "$name"
        else
            printf 'verify: %s denied\n' "$name"
            failures=$((failures + 1))
        fi
    done < "$snapshot/clients.tsv"
    (( failures == 0 ))
}

case $command_name in
    diagnose) diagnose_all ;;
    fix) fix_exports ;;
    verify) verify_all ;;
    *) usage ;;
esac
