// Code generated by mockgen. DO NOT EDIT.

package account

import "context"

// MockCommands is the generated test double used by adapter contracts.
type MockCommands struct {
	ChangeEmailFunc func(context.Context, string, string) error
	DeactivateFunc  func(context.Context, string) error
	EmailCalls      int
	DeactivateCalls int
}

func (m *MockCommands) ChangeEmail(ctx context.Context, id, email string) error {
	m.EmailCalls++
	return m.ChangeEmailFunc(ctx, id, email)
}

func (m *MockCommands) Deactivate(ctx context.Context, id string) error {
	m.DeactivateCalls++
	return m.DeactivateFunc(ctx, id)
}
