// Code generated by fakegen. DO NOT EDIT.

package worker

import (
	"context"
	"sync"

	"example.com/go-interface-slimming/internal/dispatch"
)

var _ dispatch.Service = (*FakeDispatchQueue)(nil)

type GetRunCall struct {
	Context context.Context
	ID      string
}

type CancelRunCall struct {
	Context context.Context
	ID      string
}

type ListReadyCall struct {
	Context context.Context
	Limit   int
}

type MarkDispatchedCall struct {
	Context context.Context
	ID      string
}

type RotateSigningKeyCall struct {
	Context context.Context
	Tenant  string
}

type PurgeTenantCall struct {
	Context context.Context
	Tenant  string
}

type FakeDispatchQueue struct {
	GetRunFunc           func(context.Context, string) (dispatch.Run, error)
	CancelRunFunc        func(context.Context, string) error
	ListReadyFunc        func(context.Context, int) ([]dispatch.Run, error)
	MarkDispatchedFunc   func(context.Context, string) error
	RotateSigningKeyFunc func(context.Context, string) error
	PurgeTenantFunc      func(context.Context, string) error

	mu                    sync.Mutex
	GetRunCalls           []GetRunCall
	CancelRunCalls        []CancelRunCall
	ListReadyCalls        []ListReadyCall
	MarkDispatchedCalls   []MarkDispatchedCall
	RotateSigningKeyCalls []RotateSigningKeyCall
	PurgeTenantCalls      []PurgeTenantCall
}

func (f *FakeDispatchQueue) GetRun(ctx context.Context, id string) (dispatch.Run, error) {
	f.mu.Lock()
	f.GetRunCalls = append(f.GetRunCalls, GetRunCall{Context: ctx, ID: id})
	hook := f.GetRunFunc
	f.mu.Unlock()
	if hook == nil {
		panic("FakeDispatchQueue.GetRunFunc is nil")
	}
	return hook(ctx, id)
}

func (f *FakeDispatchQueue) CancelRun(ctx context.Context, id string) error {
	f.mu.Lock()
	f.CancelRunCalls = append(f.CancelRunCalls, CancelRunCall{Context: ctx, ID: id})
	hook := f.CancelRunFunc
	f.mu.Unlock()
	if hook == nil {
		panic("FakeDispatchQueue.CancelRunFunc is nil")
	}
	return hook(ctx, id)
}

func (f *FakeDispatchQueue) ListReady(ctx context.Context, limit int) ([]dispatch.Run, error) {
	f.mu.Lock()
	f.ListReadyCalls = append(f.ListReadyCalls, ListReadyCall{Context: ctx, Limit: limit})
	hook := f.ListReadyFunc
	f.mu.Unlock()
	if hook == nil {
		panic("FakeDispatchQueue.ListReadyFunc is nil")
	}
	return hook(ctx, limit)
}

func (f *FakeDispatchQueue) MarkDispatched(ctx context.Context, id string) error {
	f.mu.Lock()
	f.MarkDispatchedCalls = append(f.MarkDispatchedCalls, MarkDispatchedCall{Context: ctx, ID: id})
	hook := f.MarkDispatchedFunc
	f.mu.Unlock()
	if hook == nil {
		panic("FakeDispatchQueue.MarkDispatchedFunc is nil")
	}
	return hook(ctx, id)
}

func (f *FakeDispatchQueue) RotateSigningKey(ctx context.Context, tenant string) error {
	f.mu.Lock()
	f.RotateSigningKeyCalls = append(f.RotateSigningKeyCalls, RotateSigningKeyCall{Context: ctx, Tenant: tenant})
	hook := f.RotateSigningKeyFunc
	f.mu.Unlock()
	if hook == nil {
		panic("FakeDispatchQueue.RotateSigningKeyFunc is nil")
	}
	return hook(ctx, tenant)
}

func (f *FakeDispatchQueue) PurgeTenant(ctx context.Context, tenant string) error {
	f.mu.Lock()
	f.PurgeTenantCalls = append(f.PurgeTenantCalls, PurgeTenantCall{Context: ctx, Tenant: tenant})
	hook := f.PurgeTenantFunc
	f.mu.Unlock()
	if hook == nil {
		panic("FakeDispatchQueue.PurgeTenantFunc is nil")
	}
	return hook(ctx, tenant)
}
