// Command eventgen renders the checked-in event protocol artifacts.
package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

type schema struct {
	Package string  `json:"package"`
	Events  []event `json:"events"`
}

type event struct {
	Name        string  `json:"name"`
	Code        string  `json:"code"`
	Description string  `json:"description"`
	Fields      []field `json:"fields"`
}

type field struct {
	GoName   string `json:"go_name"`
	JSONName string `json:"json_name"`
	Type     string `json:"type"`
}

func main() {
	schemaPath := flag.String("schema", "", "path to the event schema")
	goOutput := flag.String("go-out", "", "path for generated Go declarations")
	docOutput := flag.String("doc-out", "", "path for generated Markdown")
	flag.Parse()

	if *schemaPath == "" || *goOutput == "" || *docOutput == "" {
		fmt.Fprintln(os.Stderr, "eventgen: -schema, -go-out, and -doc-out are required")
		os.Exit(2)
	}
	if err := run(*schemaPath, *goOutput, *docOutput); err != nil {
		fmt.Fprintf(os.Stderr, "eventgen: %v\n", err)
		os.Exit(1)
	}
}

func run(schemaPath, goOutput, docOutput string) error {
	data, err := os.ReadFile(schemaPath)
	if err != nil {
		return fmt.Errorf("read schema: %w", err)
	}

	var definition schema
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&definition); err != nil {
		return fmt.Errorf("decode schema: %w", err)
	}
	if err := validate(definition); err != nil {
		return err
	}

	goSource, err := renderGo(definition)
	if err != nil {
		return err
	}
	docSource := renderDocs(definition)

	if err := writeFile(goOutput, goSource); err != nil {
		return fmt.Errorf("write Go output: %w", err)
	}
	if err := writeFile(docOutput, docSource); err != nil {
		return fmt.Errorf("write documentation output: %w", err)
	}
	return nil
}

func validate(definition schema) error {
	if !identifier(definition.Package) {
		return errors.New("schema package must be a Go identifier")
	}
	if len(definition.Events) == 0 {
		return errors.New("schema must contain at least one event")
	}

	names := make(map[string]bool)
	codes := make(map[string]bool)
	for _, item := range definition.Events {
		if !identifier(item.Name) {
			return fmt.Errorf("invalid event name %q", item.Name)
		}
		if item.Code == "" {
			return fmt.Errorf("event %s has an empty code", item.Name)
		}
		if names[item.Name] || codes[item.Code] {
			return fmt.Errorf("duplicate event name or code for %s", item.Name)
		}
		names[item.Name], codes[item.Code] = true, true

		fieldNames := make(map[string]bool)
		jsonNames := make(map[string]bool)
		for _, property := range item.Fields {
			if !identifier(property.GoName) || property.JSONName == "" {
				return fmt.Errorf("event %s has an invalid field", item.Name)
			}
			if goType(property.Type) == "" {
				return fmt.Errorf("event %s field %s has unsupported type %q", item.Name, property.GoName, property.Type)
			}
			if fieldNames[property.GoName] || jsonNames[property.JSONName] {
				return fmt.Errorf("event %s has a duplicate field", item.Name)
			}
			fieldNames[property.GoName], jsonNames[property.JSONName] = true, true
		}
	}
	return nil
}

func identifier(value string) bool {
	for index, r := range value {
		if r == '_' || unicode.IsLetter(r) || index > 0 && unicode.IsDigit(r) {
			continue
		}
		return false
	}
	return value != ""
}

func goType(value string) string {
	switch value {
	case "string":
		return "string"
	case "int":
		return "int"
	case "bool":
		return "bool"
	default:
		return ""
	}
}

func renderGo(definition schema) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString("// Code generated by eventgen; DO NOT EDIT.\n")
	output.WriteString("// Source: api/events.json\n\n")
	fmt.Fprintf(&output, "package %s\n\n", definition.Package)
	for _, item := range definition.Events {
		fmt.Fprintf(&output, "// %s is %s\n", item.Name, sentence(item.Description))
		fmt.Fprintf(&output, "type %s struct {\n", item.Name)
		for _, property := range item.Fields {
			fmt.Fprintf(
				&output,
				"\t%s %s `json:%q`\n",
				property.GoName,
				goType(property.Type),
				property.JSONName,
			)
		}
		output.WriteString("}\n\n")
		fmt.Fprintf(&output, "func (%s) EventCode() string { return %q }\n\n", item.Name, item.Code)
	}

	events := append([]event(nil), definition.Events...)
	sort.Slice(events, func(i, j int) bool { return events[i].Code < events[j].Code })
	output.WriteString("// EventCodes lists the supported wire event codes in lexical order.\n")
	output.WriteString("var EventCodes = []string{\n")
	for _, item := range events {
		fmt.Fprintf(&output, "\t%q,\n", item.Code)
	}
	output.WriteString("}\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format Go output: %w", err)
	}
	return formatted, nil
}

func renderDocs(definition schema) []byte {
	var output bytes.Buffer
	output.WriteString("<!-- Code generated by eventgen; DO NOT EDIT. -->\n")
	output.WriteString("# Event protocol\n\n")
	output.WriteString("Source: `api/events.json`\n\n")
	for eventIndex, item := range definition.Events {
		fmt.Fprintf(&output, "## `%s` (%s)\n\n", item.Code, item.Name)
		fmt.Fprintf(&output, "%s\n\n", sentence(item.Description))
		output.WriteString("| JSON field | Go field | Type |\n")
		output.WriteString("| --- | --- | --- |\n")
		for _, property := range item.Fields {
			fmt.Fprintf(
				&output,
				"| `%s` | `%s` | `%s` |\n",
				property.JSONName,
				property.GoName,
				property.Type,
			)
		}
		if eventIndex+1 < len(definition.Events) {
			output.WriteString("\n")
		}
	}
	return output.Bytes()
}

func sentence(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return "an event defined by the release protocol."
	}
	if strings.HasSuffix(value, ".") {
		return value
	}
	return value + "."
}

func writeFile(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(path), ".eventgen-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)

	if _, err := temporary.Write(data); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Chmod(0o644); err != nil {
		temporary.Close()
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}
