<#
.SYNOPSIS
    Protected driver used by verification/run_verification.py.

.DESCRIPTION
    Imports src/VcfOpsAlertTriage, runs a single triage sweep against the
    loopback mock described by the run configuration, and writes the returned
    summary object to disk as JSON. Do not edit this file; the module has to fit
    this entry point.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ConfigPath,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
$WarningPreference = 'SilentlyContinue'

Import-Module VMware.Sdk.Vcf.Ops -ErrorAction Stop -WarningAction SilentlyContinue | Out-Null

$manifest = Join-Path $PSScriptRoot '..' '..' 'src' 'VcfOpsAlertTriage' 'VcfOpsAlertTriage.psd1'
Import-Module -Name $manifest -Force -ErrorAction Stop -WarningAction SilentlyContinue

$summary = Invoke-VcfOpsAlertTriage -ConfigPath $ConfigPath
if ($null -eq $summary) {
    throw 'Invoke-VcfOpsAlertTriage returned nothing; it must return a triage summary object.'
}

$summary | ConvertTo-Json -Depth 8 | Set-Content -LiteralPath $OutputPath -Encoding utf8
