#!/usr/bin/env bash
# Acceptance harness for lifegame.sh.
# Run from the workspace root:  bash test_lifegame.sh
#
# lifegame.sh targets the kiosk boxes, where it runs with an EMPTY PATH:
# every invocation below launches it as  PATH='' "$BASH" ./lifegame.sh ...
# so any helper that forks out to an external tool (awk, grep, sort, ...)
# fails loudly here. Pure bash only.
set -u
LC_ALL=C
export LC_ALL
unset CDPATH

# run from the harness's own directory even if invoked from elsewhere
[[ $0 == */* ]] && cd -- "${0%/*}"

if [[ ! -f ./lifegame.sh ]]; then
  printf 'FAIL lifegame.sh not found in the workspace root\n'
  exit 1
fi

checks=0
fails=0

assert_eq() { # assert_eq <label> <expected> <actual>
  checks=$((checks + 1))
  if [[ "$2" == "$3" ]]; then
    return 0
  fi
  fails=$((fails + 1))
  printf 'FAIL %s\n--- expected ---\n%s\n--- actual ---\n%s\n---------------\n' "$1" "$2" "$3"
}

run() { PATH='' "$BASH" ./lifegame.sh "$@"; }

# ---- fixtures (recreated fresh on every run) --------------------------------

rm -rf fixtures
mkdir fixtures

cat > fixtures/blinker.txt <<'EOF'
! blinker, period 2
.....
.....
.###.
.....
.....
EOF

cat > fixtures/commented.txt <<'EOF'
! same blinker, buried in noise
! the parser must skip comment lines

.....
.....

! mid-grid comment
.###.
.....
.....

! trailing comment
EOF

cat > fixtures/toad.txt <<'EOF'
......
......
..###.
.###..
......
......
EOF

cat > fixtures/block.txt <<'EOF'
....
.##.
.##.
....
EOF

cat > fixtures/wide.txt <<'EOF'
.......
..###..
.......
EOF

cat > fixtures/glider.txt <<'EOF'
.#....
..#...
###...
......
......
......
EOF

cat > fixtures/dot3.txt <<'EOF'
...
.#.
...
EOF

cat > fixtures/badchar.txt <<'EOF'
..#..
..x..
..#..
EOF

cat > fixtures/ragged.txt <<'EOF'
.....
....
.....
EOF

cat > fixtures/nothing.txt <<'EOF'
! comments only

! no grid rows at all
EOF

# ---- happy-path frame transcripts -------------------------------------------

out=$(run fixtures/blinker.txt 0); st=$?
assert_eq 'blinker gen0 exit status' 0 "$st"
expected=$(cat <<'EOF'
gen 0 pop 3
.....
.....
.###.
.....
.....
EOF
)
assert_eq 'blinker 0 generations echoes the parsed grid' "$expected" "$out"

expected=$(cat <<'EOF'
gen 0 pop 3
.....
.....
.###.
.....
.....

gen 1 pop 3
.....
..#..
..#..
..#..
.....

gen 2 pop 3
.....
.....
.###.
.....
.....
EOF
)
out=$(run fixtures/blinker.txt 2); st=$?
assert_eq 'blinker exit status' 0 "$st"
assert_eq 'blinker oscillates with period 2' "$expected" "$out"

out=$(run fixtures/commented.txt 2)
assert_eq 'comment and blank lines are ignored by the parser' "$expected" "$out"

expected=$(cat <<'EOF'
gen 0 pop 6
......
......
..###.
.###..
......
......

gen 1 pop 6
......
...#..
.#..#.
.#..#.
..#...
......

gen 2 pop 6
......
......
..###.
.###..
......
......
EOF
)
out=$(run fixtures/toad.txt 2)
assert_eq 'toad oscillates with period 2' "$expected" "$out"

expected=$(cat <<'EOF'
gen 0 pop 4
....
.##.
.##.
....

gen 1 pop 4
....
.##.
.##.
....

gen 2 pop 4
....
.##.
.##.
....

gen 3 pop 4
....
.##.
.##.
....
EOF
)
out=$(run fixtures/block.txt 3)
assert_eq 'block still life never twitches' "$expected" "$out"

expected=$(cat <<'EOF'
gen 0 pop 3
.......
..###..
.......

gen 1 pop 3
...#...
...#...
...#...
EOF
)
out=$(run fixtures/wide.txt 1)
assert_eq 'non-square grid: width and height stay put' "$expected" "$out"

expected=$(cat <<'EOF'
gen 0 pop 1
...
.#.
...

gen 1 pop 0
...
...
...
EOF
)
out=$(run fixtures/dot3.txt 1)
assert_eq 'lone cell starves; empty grid renders as dots with pop 0' "$expected" "$out"

expected=$(cat <<'EOF'
gen 0 pop 5
.#....
..#...
###...
......
......
......

gen 1 pop 5
......
#.#...
.##...
.#....
......
......

gen 2 pop 5
......
..#...
#.#...
.##...
......
......

gen 3 pop 5
......
.#....
..##..
.##...
......
......

gen 4 pop 5
......
..#...
...#..
.###..
......
......

gen 5 pop 5
......
......
.#.#..
..##..
..#...
......

gen 6 pop 5
......
......
...#..
.#.#..
..##..
......

gen 7 pop 5
......
......
..#...
...##.
..##..
......

gen 8 pop 5
......
......
...#..
....#.
..###.
......

gen 9 pop 5
......
......
......
..#.#.
...##.
...#..

gen 10 pop 5
......
......
......
....#.
..#.#.
...##.

gen 11 pop 5
......
......
......
...#..
....##
...##.

gen 12 pop 5
......
......
......
....#.
.....#
...###

gen 13 pop 4
......
......
......
......
...#.#
....##

gen 14 pop 3
......
......
......
......
.....#
....##

gen 15 pop 4
......
......
......
......
....##
....##

gen 16 pop 4
......
......
......
......
....##
....##
EOF
)
out=$(run fixtures/glider.txt 16); st=$?
assert_eq 'glider exit status' 0 "$st"
assert_eq 'glider crashes into the bounded corner and settles into a block' "$expected" "$out"

# ---- error handling ----------------------------------------------------------

err_case() { # err_case <label> <expected-stderr> [arg]...
  local label=$1 expected=$2
  shift 2
  local out st err
  out=$(run "$@" 2>fixtures/.stderr); st=$?
  err=$(<fixtures/.stderr)
  assert_eq "$label: exit status" 2 "$st"
  assert_eq "$label: stderr" "$expected" "$err"
  assert_eq "$label: stdout stays empty" '' "$out"
}

usage='usage: lifegame.sh <pattern-file> <generations>'
err_case 'no arguments' "$usage"
err_case 'one argument' "$usage" fixtures/blinker.txt
err_case 'three arguments' "$usage" fixtures/blinker.txt 2 extra
err_case 'unreadable pattern file' 'error: cannot read fixtures/nope.txt' fixtures/nope.txt 1
gen_err='error: generations must be a non-negative integer'
err_case 'negative generations' "$gen_err" fixtures/blinker.txt -1
err_case 'non-numeric generations' "$gen_err" fixtures/blinker.txt abc
err_case 'fractional generations' "$gen_err" fixtures/blinker.txt 1.5
err_case 'trailing junk in generations' "$gen_err" fixtures/blinker.txt 2x
err_case 'stray character in a row' 'error: invalid character: x' fixtures/badchar.txt 1
err_case 'ragged rows' 'error: ragged pattern' fixtures/ragged.txt 1
err_case 'no grid rows at all' 'error: empty pattern' fixtures/nothing.txt 1

# ---- summary -----------------------------------------------------------------

printf '%d checks, %d failures\n' "$checks" "$fails"
if (( fails > 0 )); then
  exit 1
fi
printf 'OK\n'
