package contractmock

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
)

const (
	listOperation   = "Vcenter.TrustedInfrastructure.Hosts.Hardware.Tpm_list"
	eventOperation  = "Vcenter.TrustedInfrastructure.Hosts.Hardware.Tpm.EventLog_get"
	bundleOperation = "Appliance.SupportBundle_create$Task"
)

// Scenario contains values generated by a test at runtime.
type Scenario struct {
	SessionID         string
	Host              string
	TPM               string
	SecondaryTPM      string
	TaskID            string
	Active            bool
	MajorVersion      int64
	MinorVersion      int64
	TPMCount          int
	ExpectedListQuery string
	EventType         string
	EventData         *string
	EventTruncated    bool
	BankAlgorithm     string
	PCRs              map[string]string
}

// RequestRecord is the durable JSONL projection inspected by acceptance tests.
type RequestRecord struct {
	Method        string              `json:"method"`
	RequestURI    string              `json:"request_uri"`
	Headers       map[string][]string `json:"headers"`
	Body          string              `json:"body"`
	ContentLength int64               `json:"content_length"`
}

// Server is a loopback server whose route allow-list comes from contract.json.
type Server struct {
	URL     string
	LogPath string

	t        testing.TB
	http     *httptest.Server
	logFile  *os.File
	logMu    sync.Mutex
	routes   map[string]operation
	scenario Scenario
}

type focusedContract struct {
	Server struct {
		APIRootSuffix string `json:"api_root_suffix"`
	} `json:"server"`
	Security struct {
		Name string `json:"name"`
	} `json:"security"`
	Operations []operation `json:"operations"`
}

type operation struct {
	OperationID string `json:"operationId"`
	Method      string `json:"method"`
	Path        string `json:"path"`
}

// Start loads the protected focused contract and starts an ephemeral loopback
// server. It refuses a contract with missing, extra, or duplicate operations.
func Start(t testing.TB, contractPath string, scenario Scenario) *Server {
	t.Helper()

	contractBytes, err := os.ReadFile(contractPath)
	if err != nil {
		t.Fatalf("read focused contract: %v", err)
	}
	var contract focusedContract
	if err := json.Unmarshal(contractBytes, &contract); err != nil {
		t.Fatalf("decode focused contract: %v", err)
	}
	if contract.Server.APIRootSuffix != "/api" {
		t.Fatalf("unexpected API root suffix %q", contract.Server.APIRootSuffix)
	}
	if contract.Security.Name != "vmware-api-session-id" {
		t.Fatalf("unexpected security header %q", contract.Security.Name)
	}

	required := map[string]bool{
		listOperation:   false,
		eventOperation:  false,
		bundleOperation: false,
	}
	routes := make(map[string]operation, len(contract.Operations))
	for _, candidate := range contract.Operations {
		if _, ok := required[candidate.OperationID]; !ok {
			t.Fatalf("contract contains unnamed operation %q", candidate.OperationID)
		}
		if _, duplicate := routes[candidate.OperationID]; duplicate {
			t.Fatalf("contract repeats operation %q", candidate.OperationID)
		}
		if candidate.Method == "" || candidate.Path == "" {
			t.Fatalf("contract operation %q has an incomplete route", candidate.OperationID)
		}
		routes[candidate.OperationID] = candidate
		required[candidate.OperationID] = true
	}
	for name, present := range required {
		if !present {
			t.Fatalf("contract is missing operation %q", name)
		}
	}

	logPath := filepath.Join(t.TempDir(), "requests.jsonl")
	logFile, err := os.OpenFile(logPath, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		t.Fatalf("create request log: %v", err)
	}

	fixture := &Server{
		t:        t,
		LogPath:  logPath,
		logFile:  logFile,
		routes:   routes,
		scenario: scenario,
	}
	listener, err := net.Listen("tcp4", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("start IPv4 loopback listener: %v", err)
	}
	fixture.http = httptest.NewUnstartedServer(http.HandlerFunc(fixture.serveHTTP))
	fixture.http.Listener = listener
	fixture.http.Start()
	fixture.URL = fixture.http.URL + contract.Server.APIRootSuffix
	t.Cleanup(func() {
		fixture.http.Close()
		fixture.logMu.Lock()
		_ = fixture.logFile.Close()
		fixture.logMu.Unlock()
	})
	return fixture
}

func (s *Server) serveHTTP(writer http.ResponseWriter, request *http.Request) {
	body, _ := io.ReadAll(io.LimitReader(request.Body, 1<<20))
	_ = request.Body.Close()
	s.appendRecord(RequestRecord{
		Method:        request.Method,
		RequestURI:    request.RequestURI,
		Headers:       request.Header.Clone(),
		Body:          string(body),
		ContentLength: request.ContentLength,
	})

	if request.Header.Get("vmware-api-session-id") != s.scenario.SessionID {
		http.Error(writer, "unauthorized", http.StatusUnauthorized)
		return
	}

	if s.matches(request, listOperation, map[string]string{
		"host": s.scenario.Host,
	}) {
		if request.URL.RawQuery != s.scenario.ExpectedListQuery {
			http.Error(writer, "unexpected list query", http.StatusBadRequest)
			return
		}
		s.writeList(writer)
		return
	}
	if s.matches(request, eventOperation, map[string]string{
		"host": s.scenario.Host,
		"tpm":  s.scenario.TPM,
	}) {
		if request.URL.RawQuery != "" {
			http.Error(writer, "unexpected event query", http.StatusBadRequest)
			return
		}
		s.writeEvent(writer)
		return
	}
	if s.matches(request, bundleOperation, nil) {
		s.writeJSON(writer, http.StatusAccepted, s.scenario.TaskID)
		return
	}

	http.NotFound(writer, request)
}

func (s *Server) matches(
	request *http.Request,
	operationID string,
	values map[string]string,
) bool {
	candidate := s.routes[operationID]
	if request.Method != candidate.Method {
		return false
	}
	rawPath, rawQuery := splitContractTarget(candidate.Path)
	for name, value := range values {
		rawPath = strings.ReplaceAll(rawPath, "{"+name+"}", url.PathEscape(value))
	}
	if request.URL.EscapedPath() != "/api"+rawPath {
		return false
	}
	return rawQuery == "" || request.URL.RawQuery == rawQuery
}

func splitContractTarget(target string) (string, string) {
	path, query, found := strings.Cut(target, "?")
	if !found {
		return path, ""
	}
	return path, query
}

func (s *Server) writeList(writer http.ResponseWriter) {
	count := s.scenario.TPMCount
	if count < 0 {
		count = 0
	}
	items := make([]map[string]any, 0, count)
	if count > 0 {
		items = append(items, map[string]any{
			"tpm":           s.scenario.TPM,
			"major_version": s.scenario.MajorVersion,
			"minor_version": s.scenario.MinorVersion,
			"active":        s.scenario.Active,
		})
	}
	if count > 1 {
		items = append(items, map[string]any{
			"tpm":           s.scenario.SecondaryTPM,
			"major_version": s.scenario.MajorVersion,
			"minor_version": s.scenario.MinorVersion,
			"active":        true,
		})
	}
	s.writeJSON(writer, http.StatusOK, items)
}

func (s *Server) writeEvent(writer http.ResponseWriter) {
	event := map[string]any{
		"type":      s.scenario.EventType,
		"truncated": s.scenario.EventTruncated,
		"banks": []map[string]any{
			{
				"algorithm": s.scenario.BankAlgorithm,
				"pcrs":      s.scenario.PCRs,
			},
		},
	}
	if s.scenario.EventData != nil {
		event["data"] = *s.scenario.EventData
	}
	s.writeJSON(writer, http.StatusOK, event)
}

func (s *Server) writeJSON(writer http.ResponseWriter, status int, value any) {
	writer.Header().Set("Content-Type", "application/json")
	writer.WriteHeader(status)
	if err := json.NewEncoder(writer).Encode(value); err != nil {
		s.t.Errorf("encode mock response: %v", err)
	}
}

func (s *Server) appendRecord(record RequestRecord) {
	encoded, err := json.Marshal(record)
	if err != nil {
		s.t.Errorf("encode request record: %v", err)
		return
	}
	s.logMu.Lock()
	defer s.logMu.Unlock()
	if _, err := s.logFile.Write(append(encoded, '\n')); err != nil {
		s.t.Errorf("write request log: %v", err)
		return
	}
	if err := s.logFile.Sync(); err != nil {
		s.t.Errorf("sync request log: %v", err)
	}
}

// ReadLog reads the flushed request log independently of the server's memory.
func ReadLog(t testing.TB, path string) []RequestRecord {
	t.Helper()
	file, err := os.Open(path)
	if err != nil {
		t.Fatalf("open request log: %v", err)
	}
	defer file.Close()

	var records []RequestRecord
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		var record RequestRecord
		if err := json.Unmarshal(scanner.Bytes(), &record); err != nil {
			t.Fatalf("decode request log entry: %v", err)
		}
		records = append(records, record)
	}
	if err := scanner.Err(); err != nil {
		t.Fatalf("read request log: %v", err)
	}
	return records
}

func (r RequestRecord) String() string {
	return fmt.Sprintf("%s %s", r.Method, r.RequestURI)
}
