<#
.SYNOPSIS
    Drives the VcfVsanDp module against the loopback snapservice mock.

.DESCRIPTION
    This script is the fixed harness the verifier runs. It defines the exact
    public surface the module must expose. It writes a JSON result document that
    tests/verify.py checks alongside the mock's request log.

    Do not edit this file. Make the module satisfy it.
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string] $BaseUrl,
    [Parameter(Mandatory = $true)][string] $OutFile,
    [Parameter(Mandatory = $true)][string] $Username,
    [Parameter(Mandatory = $true)][string] $Password,
    [Parameter(Mandatory = $true)][string] $Cluster
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$result = [ordered]@{
    ok            = $false
    stage         = 'start'
    error         = $null
    sdkModules    = @()
    manifestRequiredModules = @()
    exportedNames = @()
    mandatoryParameters = [ordered]@{}
    protectionGroups = @()
    protectionGroupsFiltered = @()
    reportAll     = @()
    reportFiltered = @()
    reportEndOnly = @()
    tokenReturned = $null
}

function Save-Result {
    $json = $result | ConvertTo-Json -Depth 12
    Set-Content -LiteralPath $OutFile -Value $json -Encoding utf8
}

try {
    $uri = [uri] $BaseUrl

    $result.stage = 'import'
    $manifest = Join-Path $PSScriptRoot '../src/VcfVsanDp/VcfVsanDp.psd1'
    Import-Module $manifest -Force -ErrorAction Stop

    $result.exportedNames = @(
        (Get-Module VcfVsanDp).ExportedCommands.Keys | Sort-Object
    )
    foreach ($commandName in $result.exportedNames) {
        $names = @()
        foreach ($parameter in (Get-Command $commandName).Parameters.Values) {
            $mandatory = @($parameter.Attributes | Where-Object {
                $_ -is [System.Management.Automation.ParameterAttribute] -and $_.Mandatory
            })
            if ($mandatory.Count -gt 0) { $names += $parameter.Name }
        }
        $result.mandatoryParameters[$commandName] = @($names | Sort-Object)
    }
    $result.sdkModules = @(
        Get-Module | Where-Object { $_.Name -like 'VMware.Sdk.Vcf.*' } |
            ForEach-Object { $_.Name } | Sort-Object
    )
    $result.manifestRequiredModules = @(
        (Get-Module VcfVsanDp).RequiredModules |
            ForEach-Object { $_.Name } | Sort-Object
    )

    $result.stage = 'connect'
    $secure = ConvertTo-SecureString $Password -AsPlainText -Force
    $cred = New-Object System.Management.Automation.PSCredential ($Username, $secure)

    $session = Connect-VcfVsanDpServer `
        -Server $uri.Host `
        -Port $uri.Port `
        -Protocol $uri.Scheme `
        -Credential $cred `
        -SkipCertificateCheck

    if ($null -eq $session) { throw 'Connect-VcfVsanDpServer returned nothing.' }
    $result.tokenReturned = [string] $session.SessionId

    # --- Scenario A: unfiltered protection group listing -----------------
    # No filter arguments are supplied, so no filter keys may reach the wire.
    $result.stage = 'protection-groups'
    $pgs = @(Get-VcfVsanDpProtectionGroup -Session $session -Cluster $Cluster)
    $result.protectionGroups = @(
        $pgs | ForEach-Object {
            [ordered]@{
                ProtectionGroupId   = [string] $_.ProtectionGroupId
                ProtectionGroupName = [string] $_.ProtectionGroupName
            }
        }
    )

    # --- Scenario A2: every protection-group array filter ----------------
    # Each array element must be emitted as a repeated query key.
    $result.stage = 'protection-groups-filtered'
    $filteredPgs = @(Get-VcfVsanDpProtectionGroup `
        -Session $session `
        -Cluster $Cluster `
        -ProtectionGroupId @('pg-0001', 'pg-0003') `
        -Name @('finance-critical', 'web-tier') `
        -State @('ACTIVE') `
        -Vm @('vm-7100', 'vm-7106') `
        -ClusterPair @('pair-0001', 'pair-0002'))
    $result.protectionGroupsFiltered = @(
        $filteredPgs | ForEach-Object {
            [ordered]@{
                ProtectionGroupId   = [string] $_.ProtectionGroupId
                ProtectionGroupName = [string] $_.ProtectionGroupName
            }
        }
    )

    # --- Scenario B: complete unfiltered paginated report ----------------
    # 47 records behind a page size of 10.
    $result.stage = 'report-all'
    $all = @(Get-VcfVsanDpProtectionGroupSnapshotReport `
        -Session $session -Cluster $Cluster -PageSize 10)
    $result.reportAll = @(
        $all | ForEach-Object {
            [ordered]@{
                ProtectionGroupId   = [string] $_.ProtectionGroupId
                SnapshotId          = [string] $_.SnapshotId
                SnapshotName        = [string] $_.SnapshotName
                Status              = [string] $_.Status
                SnapshotType        = [string] $_.SnapshotType
                CreationTime        = [string] $_.CreationTime
                ExpirationTime      = [string] $_.ExpirationTime
                Deleted             = [bool]   $_.Deleted
            }
        }
    )

    # --- Scenario C: filtered paginated report ---------------------------
    # Time window and protection group filters are supplied and must appear.
    $result.stage = 'report-filtered'
    $filtered = @(Get-VcfVsanDpProtectionGroupSnapshotReport `
        -Session $session `
        -Cluster $Cluster `
        -PageSize 5 `
        -StartTime '2026-05-02T00:00:00.000Z' `
        -EndTime   '2026-05-04T12:00:00.000Z' `
        -ProtectionGroupId @('pg-0001', 'pg-0003'))
    $result.reportFiltered = @(
        $filtered | ForEach-Object {
            [ordered]@{
                ProtectionGroupId   = [string] $_.ProtectionGroupId
                SnapshotId          = [string] $_.SnapshotId
                CreationTime        = [string] $_.CreationTime
            }
        }
    )

    # --- Scenario D: one-sided optional time filter ---------------------
    # EndTime is supplied without StartTime; start_time must remain absent.
    $result.stage = 'report-end-only'
    $endOnly = @(Get-VcfVsanDpProtectionGroupSnapshotReport `
        -Session $session `
        -Cluster $Cluster `
        -PageSize 100 `
        -EndTime '2026-05-04T12:00:00.000Z')
    $result.reportEndOnly = @(
        $endOnly | ForEach-Object {
            [ordered]@{
                ProtectionGroupId = [string] $_.ProtectionGroupId
                SnapshotId        = [string] $_.SnapshotId
                CreationTime      = [string] $_.CreationTime
            }
        }
    )

    $result.stage = 'disconnect'
    Disconnect-VcfVsanDpServer -Session $session

    $result.stage = 'done'
    $result.ok = $true
}
catch {
    $result.error = ($_ | Out-String)
}
finally {
    Save-Result
}

if (-not $result.ok) { exit 1 }
exit 0
