// Code generated by eventgen; DO NOT EDIT.
// Source: api/events.json

package eventwire

// BuildQueued is A build entered the release queue.
type BuildQueued struct {
	BuildID    string `json:"build_id"`
	Repository string `json:"repository"`
	Attempt    int    `json:"attempt"`
}

func (BuildQueued) EventCode() string { return "build.queued" }

// BuildReleased is A build artifact was released.
type BuildReleased struct {
	BuildID        string `json:"build_id"`
	ArtifactDigest string `json:"artifact_digest"`
}

func (BuildReleased) EventCode() string { return "build.released" }

// EventCodes lists the supported wire event codes in lexical order.
var EventCodes = []string{
	"build.queued",
	"build.released",
}
