#!/usr/bin/env python3
"""Render the Hugging Face dataset card from the single house template.

Every dataset moonshiner generates gets this template. The card is never
hand-written: this program renders it from ``config.json``, the seed corpus,
and the ACTUAL rows being published — so the mix (languages, task categories,
coding vs security), the teacher/judge configuration, the tool surface, split
sizes, and the model attestation rate always follow the data.

Two stages share the one template:

- ``release`` (the ``card`` pipeline phase): renders from the validated
  next-step export in ``data/hf-publish/traces.jsonl``.
- ``preview`` (used by ``publish_preview``): renders while generation is still
  running, from the verified, attested whole-trajectory rows published so far.
  Sections that only exist after screening state that plainly instead of
  carrying fabricated numbers.

Style mirrors the sibling house cards — rich YAML front-matter, a regenerable
``screened-snapshot`` status block, and provenance + limitations sections that
document the verification and independent-judge screening effort behind the
corpus. Every card opens with the moonshiner attribution link. This phase
calls no model; it is safe to run offline.
"""
from __future__ import annotations

import json
import shutil
from collections import Counter
from pathlib import Path
from statistics import median

from common import CONFIG, DATA, ROOT
from runtimes.pi import OFFERED_TOOLS

PUBLISH_DIR = DATA / "hf-publish"
TRACES = PUBLISH_DIR / "traces.jsonl"
CARD = PUBLISH_DIR / "README.md"
SEEDS_DIR = ROOT / "tasks" / "seeds"
CAPABILITY_SEEDS_DIR = ROOT / "tasks" / "behavior-seeds"
BANNER = PUBLISH_DIR / "moonshiner-dataset-banner.png"

MOONSHINER_URL = "https://github.com/greghavens/moonshiner"
ATTRIBUTION = (
    f"> Generated by **[moonshiner]({MOONSHINER_URL})** — an open harness for\n"
    "> distilling verified instruction-following, tool-use, and agentic coding traces.")


def _banner_source() -> Path:
    """Resolve this project's configured banner while keeping one Hub filename."""
    profile = CONFIG.get("model_profile") or {}
    configured = str((CONFIG.get("publish") or {}).get("banner_source")
                     or profile.get("banner_source")
                     or "assets/moonshiner-dataset-banner.png")
    path = Path(configured).expanduser()
    return path if path.is_absolute() else ROOT / path

# One row per published column, in the exact export order, with a consumer-facing
# description. Kept in lockstep with export_hf_next_steps.PUBLISH_KEY_ORDER.
COLUMN_DOCS: tuple[tuple[str, str, str], ...] = (
    ("task", "string", "Seed/task id the source trajectory solved."),
    ("source_trajectory_id", "string",
     "Stable id of the whole-session trajectory this row is a prefix of."),
    ("source_trajectory_sha256", "string",
     "Content hash of the source trajectory (provenance)."),
    ("lang", "string", "Primary language (`en` for instruction-following; programming language for coding tasks)."),
    ("category", "string", "Task kind (build, debug, feature, refactor, …)."),
    ("domain", "string", "coding, security, or harness."),
    ("verifier", "string", "How the source trajectory was verified before export."),
    ("split", "string", "train or val (trajectory-disjoint)."),
    ("teacher_runtime", "string", "Coding-agent runtime that produced the trace."),
    ("teacher_model", "string", "Teacher model id."),
    ("reasoning_effort", "string", "Teacher thinking/reasoning level."),
    ("provider", "string", "Serving provider for the teacher model."),
    ("observed_models", "list[string]",
     "Model id(s) actually observed in the attested stream."),
    ("model_attested", "bool",
     "Both the agent stream and the upstream proxy confirmed the model."),
    ("trace_format", "string", "Native runtime trace format before normalization."),
    ("tools_used", "list[string]", "Tools the assistant actually called."),
    ("derivation", "string", "How the next-step row was derived."),
    ("assistant_step", "int", "This row's position (1..N) among assistant turns."),
    ("assistant_steps", "int", "Total assistant turns in the source trajectory."),
    ("target_message_index", "int", "Index of the final (target) assistant message."),
    ("original_n_messages", "int", "Message count of the full source trajectory."),
    ("n_messages", "int", "Message count in this cumulative-prefix row."),
    ("messages", "list[object]",
     "The conversation (system/user/assistant/tool) in OpenAI chat format."),
    ("tools", "string",
     "JSON-encoded tool schemas — the full offered action space for the row."),
)

# The interim shape published while generation runs: one row per verified,
# attested whole trajectory. Kept in lockstep with publish_preview row keys.
PREVIEW_COLUMN_DOCS: tuple[tuple[str, str, str], ...] = (
    ("task", "string", "Seed/task id the trajectory solved."),
    ("lang", "string", "Primary programming language."),
    ("category", "string", "Task kind (build, debug, feature, refactor, …)."),
    ("teacher_runtime", "string", "Coding-agent runtime that produced the trace."),
    ("teacher_model", "string", "Teacher model id."),
    ("provider", "string", "Serving provider for the teacher model."),
    ("reasoning_effort", "string", "Teacher thinking/reasoning level."),
    ("model_attested", "bool",
     "Both the agent stream and the upstream proxy confirmed the model."),
    ("observed_models", "list[string]",
     "Model id(s) actually observed in the attested stream."),
    ("trace_format", "string", "Native runtime trace format before normalization."),
    ("n_messages", "int", "Message count in the trajectory."),
    ("messages", "list[object]",
     "The full session (system/user/assistant/tool) in OpenAI chat format."),
)

BASE_TAGS = (
    "traces", "code", "agentic", "tool-use", "coding-agent", "coding-agents",
    "agent-traces", "instruction-following", "function-calling",
    "parallel-tool-calling", "multi-turn", "sft", "distillation", "reasoning",
    "chain-of-thought", "cot",
)
SECURITY_TAGS = (
    "cybersecurity", "security", "secure-coding", "defensive-security",
    "vulnerability-detection", "static-analysis", "code-review", "cwe", "owasp",
)


def _load_rows(path: Path) -> list[dict]:
    if not path.exists():
        raise SystemExit(
            f"no published export at {path} — run `export-next` first")
    # Stream the large cumulative export so rendering does not also hold a
    # second full-file string and split-line copy in memory.
    with path.open() as handle:
        rows = [json.loads(line) for line in handle if line.strip()]
    if not rows:
        raise SystemExit(f"published export {path} is empty")
    return rows


def _size_category(n: int) -> str:
    if n < 1_000:
        return "n<1K"
    if n < 10_000:
        return "1K<n<10K"
    if n < 100_000:
        return "10K<n<100K"
    if n < 1_000_000:
        return "100K<n<1M"
    return "1M<n<10M"


def _pct(part: int, whole: int) -> int:
    return round(100 * part / whole) if whole else 0


def _pct1(part: int, whole: int) -> str:
    return f"{100 * part / whole:.1f}%" if whole else "0.0%"


def _human_size(size: int) -> str:
    """Match Hugging Face's decimal dataset-size convention."""
    if size < 1_000_000:
        return f"{size / 1_000:.0f} kB"
    if size < 1_000_000_000:
        return f"{int(size / 1_000_000)} MB"
    return f"{size / 1_000_000_000:.1f} GB"


def _display_model(model_id: str) -> str:
    from model_profile import display_name
    return display_name(model_id)


def _capability_seed_ids() -> set[str]:
    """Identify instruction-following/tool-use trajectories in legacy rows."""
    ids: set[str] = set()
    for path in CAPABILITY_SEEDS_DIR.glob("*.json"):
        try:
            seed_id = json.loads(path.read_text()).get("id")
        except (OSError, json.JSONDecodeError):
            continue
        if isinstance(seed_id, str):
            ids.add(seed_id)
    return ids


def _display_language(value: str | None) -> str:
    aliases = {
        "non-code": "English", "seed-authoring": "English", "en": "English",
        "py": "Python", "python": "Python", "ts": "TypeScript",
        "typescript": "TypeScript", "js": "JavaScript", "javascript": "JavaScript",
        "go": "Go", "rust": "Rust", "java": "Java", "ruby": "Ruby",
        "csharp": "C#", "cpp": "C++", "c": "C", "bash": "Bash",
        "zsh": "Zsh", "powershell": "PowerShell", "asm": "Assembly",
    }
    raw = str(value or "unknown")
    return aliases.get(raw.casefold(), raw)


def _trajectories(rows: list[dict]) -> dict[str, dict]:
    """Collapse rows to one entry per source trajectory (release: prefix rows
    share a source_trajectory_id; preview: each row IS one trajectory)."""
    view: dict[str, dict] = {}
    capability_ids = _capability_seed_ids()
    for row in rows:
        tid = row.get("source_trajectory_id") or row.get("task")
        domain = row.get("domain")
        if row.get("task") in capability_ids:
            domain = "instruction-following/tool-use"
        language = _display_language(row.get("lang"))
        if row.get("task") in capability_ids:
            language = "English"
        entry = view.setdefault(tid, {
            "task": row.get("task"),
            "lang": language,
            "category": row.get("category") or "unknown",
            "domain": domain or "coding",
            "split": row.get("split"),
            "steps": row.get("assistant_steps") or 0,
            "tools_used": set(),
        })
        entry["tools_used"].update(row.get("tools_used") or [])
        if not entry["steps"] and row.get("messages"):
            entry["steps"] = sum(1 for m in row["messages"]
                                 if m.get("role") == "assistant")
        if not entry["tools_used"] and row.get("messages"):
            entry["tools_used"].update(
                call.get("function", {}).get("name")
                for m in row["messages"]
                for call in (m.get("tool_calls") or [])
                if call.get("function", {}).get("name"))
    return view


def _offered_tools(rows: list[dict]) -> list[str]:
    for row in rows:
        try:
            schemas = json.loads(row.get("tools") or "[]")
        except json.JSONDecodeError:
            continue
        names = [s.get("function", {}).get("name") for s in schemas
                 if isinstance(s, dict)]
        names = [n for n in names if n]
        if names:
            return names
    return list(OFFERED_TOOLS)


def _mix_table(counter: Counter, total: int, head: str) -> str:
    lines = [f"| {head} | Trajectories | Share |", "| --- | ---: | ---: |"]
    for key, count in counter.most_common():
        if not count:
            continue
        lines.append(f"| `{key}` | {count:,} | {_pct1(count, total)} |")
    return "\n".join(lines)


def _program_assignments() -> dict[str, str]:
    """Load catalog assignments, supplementing the source catalog with the
    installed corpus catalog so resumed traces retain their original labels."""
    by_id: dict[str, str] = {}
    paths = (DATA.parent / "corpora" / "active" / "SEED_CATALOG.json",
             ROOT / "SEED_CATALOG.json")
    for path in paths:
        try:
            catalog = json.loads(path.read_text())
        except (OSError, json.JSONDecodeError):
            continue
        by_id.update({item.get("id"): item.get("program")
                      for items in (catalog.get("categories") or {}).values()
                      for item in items
                      if isinstance(item, dict) and item.get("id") and item.get("program")})
    return by_id


def _published_program(task: str | None, category: str | None,
                       by_id: dict[str, str]) -> str:
    if task in by_id:
        return by_id[task]
    if category and category != "unknown":
        return str(category).replace("-", " ").capitalize()
    return "Uncategorized"


def _program_mix(trajectories: dict[str, dict]) -> Counter:
    """Use catalog programs, falling back to explicit published categories."""
    by_id = _program_assignments()
    result: Counter = Counter()
    for entry in trajectories.values():
        result[_published_program(entry.get("task"), entry.get("category"), by_id)] += 1
    return result


def _program_row_mix(rows: list[dict]) -> Counter:
    """Count training rows using the catalog's explicit program assignment."""
    by_id = _program_assignments()
    return Counter(_published_program(row.get("task"), row.get("category"), by_id)
                   for row in rows)


def _program_table(counter: Counter, total: int, row_counter: Counter,
                   total_rows: int) -> str:
    try:
        programs = json.loads((ROOT / "SEED_CATALOG.json").read_text()).get("programs") or {}
    except (OSError, json.JSONDecodeError):
        programs = {}
    lines = ["| kind | trajectories | share | row share | flavor |",
             "|---|---:|---:|---:|---|"]
    for name, count in counter.most_common():
        if count:
            lines.append(
                f"| {name} | {count:,} | {_pct1(count, total)} | "
                f"{_pct1(row_counter.get(name, 0), total_rows)} | "
                f"{programs.get(name, {}).get('description', 'Accepted trajectories grouped by their explicit published dataset category.')} |")
    return "\n".join(lines)


def _front_matter(pretty_name: str, license_id: str, tags: list[str],
                  size_cat: str, has_security: bool) -> str:
    task_categories = ["text-generation"]
    if has_security:
        task_categories.append("question-answering")
    lines = ["---", f"pretty_name: {pretty_name}", f"license: {license_id}",
             "language:", "  - en", "annotations_creators:",
             "  - machine-generated", "task_categories:"]
    lines += [f"  - {cat}" for cat in task_categories]
    lines += ["size_categories:", f"  - {size_cat}", "tags:"]
    # JSON string quoting is valid YAML and prevents numeric-looking model
    # components (for example `5`) from becoming non-string tag values.
    lines += [f"  - {json.dumps(str(tag))}" for tag in tags]
    lines.append("---")
    return "\n".join(lines)


def build_card(rows: list[dict], *, stage: str = "release") -> str:
    if stage not in ("release", "preview"):
        raise ValueError(f"unknown card stage: {stage!r}")
    preview = stage == "preview"
    publish = CONFIG.get("publish", {})
    teacher = CONFIG.get("teacher", {})
    judge = CONFIG.get("judge", {})

    trajectories = _trajectories(rows)
    total_traj = len(trajectories)
    total_rows = len(rows)
    row_splits = Counter(row.get("split") for row in rows)
    traj_splits = Counter(entry["split"] for entry in trajectories.values())
    categories = _program_mix(trajectories)
    category_rows = _program_row_mix(rows)
    languages = Counter(entry["lang"] for entry in trajectories.values())
    domains = Counter(entry["domain"] for entry in trajectories.values())
    instruction_trajectories = domains.get("instruction-following/tool-use", 0)
    coding_trajectories = total_traj - instruction_trajectories
    step_counts = [entry["steps"] for entry in trajectories.values()
                   if entry["steps"]]
    used_tools = sorted({tool for entry in trajectories.values()
                         for tool in entry["tools_used"]})
    offered_tools = _offered_tools(rows)
    attested = sum(1 for row in rows if row.get("model_attested"))
    attest_pct = _pct(attested, total_rows)
    has_security = domains.get("security", 0) > 0

    teacher_model = teacher.get("model", "the teacher model")
    teacher_runtime = teacher.get("runtime", "pi")
    runtime_config = (CONFIG.get("runtimes") or {}).get(teacher_runtime) or {}
    provider = (rows[0].get("provider") if rows else None) \
        or teacher.get("provider") or runtime_config.get("display_provider") \
        or runtime_config.get("provider") or "the serving provider"
    reasoning = teacher.get("reasoning", "max")
    judge_model = judge.get("model", "an independent reviewer")
    judge_runtime = judge.get("runtime", "codex")
    profile = CONFIG.get("model_profile") or {}
    model_display = (publish.get("model_display")
                     or (profile.get("display_name")
                         if profile.get("id") == teacher_model else None)
                     or _display_model(teacher_model))

    default_pretty = f"{model_display} Agent Traces"
    pretty_name = publish.get("pretty_name") or default_pretty
    license_id = publish.get("license") or "cc-by-4.0"
    hub_id = publish.get("hf_dataset") or "<namespace>/<dataset>"

    # Dataset discovery tags describe the data and its intended use. Teacher
    # model, provider, and runtime belong in provenance—not in this tag list.
    tags = list(BASE_TAGS)
    if has_security:
        tags += [t for t in SECURITY_TAGS if t not in tags]
    size_cat = _size_category(total_rows)

    coding_seed_count = sum(1 for child in SEEDS_DIR.iterdir() if child.is_dir()) \
        if SEEDS_DIR.exists() else 0
    capability_seed_count = len(_capability_seed_ids())
    seed_count = coding_seed_count + capability_seed_count
    lang_list = ", ".join(f"`{lang}`" for lang, _ in languages.most_common()) \
        or "landing with the first published trajectories"
    step_line = (f"{min(step_counts)}–{max(step_counts)} "
                 f"(median {int(median(step_counts))})") if step_counts else "n/a"

    if preview:
        intro_tail = (
            "and is published only after its work **verifiably passes** — "
            "acceptance tests green and protected test files unmodified "
            "(hash-checked) — with **dual model attestation**. This is a live, "
            "growing drop: each row is one whole-session trajectory, appended "
            f"as it finishes. At release the corpus is screened by "
            f"**{judge_model}** (`{judge_runtime}`) and re-exported as "
            "cumulative next-step prefixes (one training row per assistant "
            "turn), replacing this file wholesale.")
    else:
        intro_tail = (
            "and is kept only after its work **verifiably passes** and clears an\n"
            f"independent screen by **{judge_model}** (`{judge_runtime}`). "
            "Rows are exported as\n"
            "**cumulative next-step prefixes**: one training row per assistant "
            "turn, each\ncarrying the full prior context and targeting exactly "
            "the next action.")

    # One unbroken sentence: Markdown collapses newlines, but keeping the computed
    # counts on a single logical line keeps the raw card clean and greppable.
    if preview:
        snapshot = (
            f"**Generation in progress:** {total_traj:,} verified, "
            f"model-attested trajectories published so far, drawn from a corpus "
            f"of {seed_count:,} verifiable seeds; this file grows "
            f"continuously as new traces finish. Model-attested: "
            f"**{attest_pct}%**. At release the screened next-step export "
            f"replaces this file and this card regenerates from the published "
            f"rows.")
    else:
        snapshot = (
            f"**This snapshot:** {total_rows:,} next-step rows across "
            f"{total_traj:,} accepted trajectories "
            f"(train {traj_splits.get('train', 0):,} / "
            f"val {traj_splits.get('val', 0):,} trajectories; "
            f"{row_splits.get('train', 0):,} / {row_splits.get('val', 0):,} rows). "
            f"Model-attested: **{attest_pct}%**. Drawn from a corpus of "
            f"{seed_count:,} verifiable seeds. Regenerate this card from the "
            f"published rows with `moonshiner card`.")
    if instruction_trajectories:
        snapshot += (
            f" Composition by accepted trajectory: **{instruction_trajectories:,} "
            f"instruction-following/tool-use ({_pct1(instruction_trajectories, total_traj)})** "
            f"and **{coding_trajectories:,} coding ({_pct1(coding_trajectories, total_traj)})**.")

    judge_bullet = (
        f"- **Independent judge at release.** A separate reviewer "
        f"(`{judge_model}`) screens every trajectory before the final export; "
        "the teacher does not grade itself."
        if preview else
        f"- **Independent judge.** A separate reviewer (`{judge_model}`) "
        "screens each\n  trajectory for quality; the teacher does not grade "
        "itself.")

    tools_bullet = (
        "- **One tool surface for every task.** Each trajectory ran with the "
        "same offered\n  action space (listed below); the release export "
        "carries the full JSON tool\n  schemas per row."
        if preview else
        "- **Full offered tool surface.** Every row's `tools` lists the "
        "complete action\n  space the teacher had, not only the tools a given "
        "trajectory happened to call.")

    schema_docs = PREVIEW_COLUMN_DOCS if preview else COLUMN_DOCS
    schema_rows = "\n".join(
        f"| `{name}` | {dtype} | {desc} |" for name, dtype, desc in schema_docs)
    schema_note = (
        "\n\nAt release, rows switch to the cumulative next-step schema used by "
        "the sibling\ndatasets (`source_trajectory_id`, `split`, "
        "`assistant_step`, `target_message_index`,\nJSON-encoded `tools`, …)."
        if preview else "")

    layout_para = (
        "A single file, `traces.jsonl`, holds one row per **whole trajectory** "
        "— the full\nsession in `messages`. The file is rewritten and "
        "re-uploaded automatically as new\nverified trajectories land. At "
        "release it is replaced by the validated cumulative\nnext-step export: "
        "one row per assistant turn, exact-prefix continuity and\n"
        "trajectory-disjoint train/val splits checked before publication."
        if preview else
        "The canonical `traces.jsonl` holds every row. Bounded files under "
        "`viewer/` are byte-for-byte row-preserving shards used only by the "
        "Hugging Face viewer. For each source "
        "trajectory the\nexport emits an ordered, gap-free sequence of "
        "**cumulative prefixes**: step *k*\nis exactly the first *k* assistant "
        "turns with all intervening user/tool\nmessages, and its final message "
        "(`target_message_index`) is the assistant action\nto learn. All rows "
        "from one trajectory stay on the **same side** of the\ntrain/val "
        "split, so no prefix leaks across the boundary. The export is "
        "validated\nfor exact-prefix continuity and split-disjointness before "
        "publication.")

    screening_bullet = (
        "- **Screening.** Deterministic gates (acceptance tests + "
        "protected-file hashes)\n  are already applied to every published "
        f"trajectory; the independent `{judge_model}`\n  review gates the "
        "final release. Standing rejections may be retraced and\n  "
        "re-screened."
        if preview else
        "- **Screening.** Deterministic gates (acceptance tests + "
        "protected-file hashes)\n  then an independent "
        f"`{judge_model}` review; only trajectories that clear both\n  are "
        "built. Standing rejections may be retraced and re-screened.")

    derivation = ("whole-session trajectories (release: "
                  "cumulative-next-step-prefixes)" if preview
                  else (rows[0].get("derivation",
                                    "cumulative-next-step-prefixes")
                        if rows else "cumulative-next-step-prefixes"))

    structure_limit = (
        "- **Pre-screening drop.** Every published row passed deterministic "
        "verification\n  and attestation, but the independent judge screen "
        "happens at release; a small\n  share may be removed or replaced in "
        "the final export."
        if preview else
        "- **Cumulative prefixes.** Rows from one trajectory share context "
        "and are highly\n  correlated; treat the **trajectory** "
        "(`source_trajectory_id`), not the row, as\n  the independent unit "
        "for held-out splits or de-duplication.")

    security_bullet = (
        "\n- **Held-out security grading.** Security trajectories are graded "
        "against hidden reference findings (CWE/OWASP mapping and path-line "
        "recall); the teacher never sees the answer key, and hostile fixtures "
        "run under a bubblewrap sandbox."
        if has_security else "")

    security_program = (
        "\n- **defensive security** — blind vulnerability findings and repair "
        "chains, rejection-sampled and graded against a firewalled answer key."
        if has_security else "")

    security_limit = (
        "\n- **Authorization scope.** Security material is for defensive use — "
        "detection, secure coding, and code review. It documents classes of "
        "weakness, not exploitation playbooks."
        if has_security else "")

    intended_security = (
        "\n- Training or evaluating **defensive secure-coding and code-review** "
        "agents." if has_security else "")

    file_size = TRACES.stat().st_size if TRACES.is_file() else 0
    return f"""{_front_matter(pretty_name, license_id, tags, size_cat, has_security)}

# {pretty_name}

![Moonshiner — {model_display} instruction following, tool use, and coding](./{BANNER.name})

<div align="center">
  <h2>{total_traj:,} TRAJECTORIES · {total_rows:,} TRAINING ROWS · {_human_size(file_size)}</h2>
</div>

{ATTRIBUTION}

Behavior-preserving **instruction-following, tool-use, and agent trajectories**
from **{model_display}** (`{teacher_model}`). The category and row-share tables
below describe the actual mix seen during training rather than assuming a
particular task domain.

**This is an actively growing dataset. More is coming**: additional training
programs and substantially more sessions will be added to this same repo.

## What makes it different

- **All real model trajectories.** Every row is a cumulative prefix of a genuine
  {model_display} session captured end-to-end. The agent's causal exploration, tool
  arguments, results, corrections, and final responses are retained.
- **One next step per row.** A trajectory with N assistant turns produces N
  rows. Row k contains the complete context through assistant turn k; that final
  assistant message is the sole training target.
- **Runtime-normalized.** Runtime plumbing, UI decoration, control sequences,
  and verbose success boilerplate are removed or canonicalized while causal
  context remains.
- **Independently verified.** Coding sessions must pass deterministic tests and
  protected-file checks. Instruction-following sessions must pass deterministic
  tool-call, staging, argument, and response-constraint checks. Every retained
  trajectory also clears independent review.

## Task mix

High-level training programs, calculated from accepted trajectories using the
same program mapping published in the seed catalog:

{_program_table(categories, total_traj, category_rows, total_rows)}

## Languages (current drop)

{lang_list}

## Schema

Each row:

| column | type | contents |
|---|---|---|
| `task` | string | stable task id |
| `lang` | string | English (`en`) or primary programming language |
| `category` | string | detailed recipe category |
| `split` | string | trajectory-disjoint `train` or `val` partition |
| `assistant_step` | int | 1-based target assistant turn |
| `assistant_steps` | int | assistant turns in the source trajectory |
| `target_message_index` | int | index of the final assistant target |
| `n_messages` | int | cumulative message count through the target |
| `messages` | list of objects | cumulative context ending at the target |
| `tools` | string (JSON) | tool schemas available in the session |

`messages` is native JSON. `tools` is JSON-encoded because parameter schemas
are heterogeneous.

## Layout

Everything ships in one data file: `traces.jsonl`. It currently contains
{total_rows:,} cumulative next-step rows derived from {total_traj:,} accepted
trajectories over disjoint train and validation tasks.

When training from the cumulative view, supervise only the final assistant
message in each row. Supervising every assistant span would repeatedly
overweight early steps because those spans recur as context in later prefixes.

## Intended use

Supervised fine-tuning of instruction-following, tool-calling, and coding
agents, plus analysis of multi-step planning, parallel calls, tool selection,
state tracking, build-test-fix loops, and verification-driven completion.

## Provenance

Generated with {model_display} (`{teacher_model}`), then filtered by deterministic verification and
explicit Codex acceptance review. Codex supplies no demonstration content; it
only judges or requests replacement of candidate traces. Provider credentials,
user keys, and host-identifying data are scrubbed before publication.

## License

[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) — free for training,
research, commercial products, modification, redistribution, and inclusion in
other datasets or corpora, with attribution.

Suggested attribution:

> {pretty_name} —
> https://huggingface.co/datasets/{hub_id}
"""


def main() -> None:
    rows = _load_rows(TRACES)
    CARD.parent.mkdir(parents=True, exist_ok=True)
    banner_source = _banner_source()
    if banner_source.is_file():
        shutil.copy2(banner_source, BANNER)
    CARD.write_text(build_card(rows))
    print(f"wrote {CARD}: dataset card for {len(rows):,} rows "
          f"({len(_trajectories(rows)):,} trajectories)")


if __name__ == "__main__":
    main()
