"""Per-trajectory token-level logprob sidecars in columnar form.

A trace's logprobs are not part of its trace. At ``top_logprobs=100`` one
generated token carries a hundred (id, logprob) pairs, so a 60K-token
trajectory is tens of megabytes -- inlined into the trace JSON it would make
every trace file unreadable and turn the dataset loader into a decoder of
numbers nothing but the trainer ever reads. They are written beside the trace
instead, one Parquet file per trajectory, keyed so a row can be put back
against the exact assistant token it belongs to.

The key is ``(trajectory_id, assistant_turn_index, token_index)``.
``assistant_turn_index`` counts assistant messages in the canonical trace from
1, which is deliberately the same numbering ``expand_next_steps`` publishes as
``assistant_step``: a published next-step row and the distributions that
produced its target join without a translation table.

Two decisions here exist to protect the training target, and both are
load-bearing:

*Ids, never strings.* Every token is stored as the integer id the server
sampled. A sidecar that stored decoded text would force the loader to
re-tokenize it, and a tokenizer round-trip that disagrees with the server by
even one token shifts every target against its distribution from that point
on. Nothing raises; the loss simply trains toward the wrong column and the
curve looks fine.

*No renormalization.* The top-K is a truncated head of the real distribution
and its probabilities do not sum to one. That missing mass is information --
it says how much of the model's belief lies outside the K captured -- and a
KL objective can account for it only if it is still there. Renormalizing on
write would silently discard it.

``logprob`` is stored as float32. Values run to about -25, where float32 holds
roughly six exact decimal digits, far below the resolution any KL term
resolves; float64 would double a file whose size is the reason this module
exists.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path

import pyarrow as pa
import pyarrow.parquet as pq

SCHEMA_VERSION = "1"

# The only segment a sidecar ever contains. Prompt and tool-result tokens are
# not generated by the model and carry no distribution, so they have no rows
# here at all. The column is written anyway: a reader must be able to see the
# boundary stated in the schema rather than infer it from an absence, which is
# indistinguishable from a capture that silently dropped them.
ASSISTANT_SEGMENT = "assistant_generated"

SCHEMA = pa.schema([
    pa.field("trajectory_id", pa.string(), nullable=False),
    pa.field("assistant_turn_index", pa.int32(), nullable=False),
    pa.field("token_index", pa.int32(), nullable=False),
    pa.field("token_id", pa.int32(), nullable=False),
    pa.field("logprob", pa.float32(), nullable=False),
    pa.field("top_token_ids", pa.list_(pa.int32()), nullable=False),
    pa.field("top_logprobs", pa.list_(pa.float32()), nullable=False),
    pa.field("segment", pa.dictionary(pa.int32(), pa.string()), nullable=False),
    pa.field("top_k_requested", pa.int32(), nullable=False),
    pa.field("prompt_token_count", pa.int32(), nullable=True),
    pa.field("finish_reason", pa.dictionary(pa.int32(), pa.string()),
             nullable=True),
    pa.field("model", pa.dictionary(pa.int32(), pa.string()), nullable=True),
])

METADATA_PREFIX = "moonshiner.logprobs."


class LogprobsUnavailable(RuntimeError):
    """The server cannot deliver the requested token distributions.

    Raised instead of degrading. Every degradation available here -- fewer
    logprobs than asked for, decoded strings instead of ids, a turn captured
    without them -- produces a sidecar that still loads and still trains, and
    trains against the wrong thing.
    """


@dataclass
class GeneratedToken:
    """One sampled token and the truncated distribution it was drawn from."""
    token_id: int
    logprob: float
    top_token_ids: list[int]
    top_logprobs: list[float]


@dataclass
class TurnLogprobs:
    """Every generated token of one assistant turn, in generation order."""
    assistant_turn_index: int
    tokens: list[GeneratedToken] = field(default_factory=list)
    model: str | None = None
    finish_reason: str | None = None
    prompt_token_count: int | None = None


def _validate(turns: list[TurnLogprobs], top_k: int) -> None:
    seen: set[int] = set()
    for turn in turns:
        if turn.assistant_turn_index < 1:
            raise LogprobsUnavailable(
                "assistant_turn_index is 1-based to match the published "
                f"assistant_step; got {turn.assistant_turn_index}")
        if turn.assistant_turn_index in seen:
            raise LogprobsUnavailable(
                f"assistant turn {turn.assistant_turn_index} captured twice")
        seen.add(turn.assistant_turn_index)
        for index, token in enumerate(turn.tokens):
            if len(token.top_token_ids) != len(token.top_logprobs):
                raise LogprobsUnavailable(
                    f"turn {turn.assistant_turn_index} token {index}: "
                    f"{len(token.top_token_ids)} ids against "
                    f"{len(token.top_logprobs)} logprobs")
            # A server that quietly returns fewer alternatives than asked for
            # has changed the objective without saying so.
            if len(token.top_token_ids) > top_k:
                raise LogprobsUnavailable(
                    f"turn {turn.assistant_turn_index} token {index}: server "
                    f"returned {len(token.top_token_ids)} alternatives for a "
                    f"requested top_logprobs={top_k}")


def write_sidecar(path: Path, *, trajectory_id: str, turns: list[TurnLogprobs],
                  top_k: int, system_prompt: str | None = None,
                  extra_metadata: dict[str, str] | None = None) -> dict:
    """Write one trajectory's distributions; return a summary of what landed."""
    if not trajectory_id:
        raise LogprobsUnavailable("a sidecar needs a trajectory id to align to")
    _validate(turns, top_k)

    columns: dict[str, list] = {name: [] for name in SCHEMA.names}
    for turn in sorted(turns, key=lambda item: item.assistant_turn_index):
        for token_index, token in enumerate(turn.tokens):
            columns["trajectory_id"].append(trajectory_id)
            columns["assistant_turn_index"].append(turn.assistant_turn_index)
            columns["token_index"].append(token_index)
            columns["token_id"].append(token.token_id)
            columns["logprob"].append(token.logprob)
            columns["top_token_ids"].append(list(token.top_token_ids))
            columns["top_logprobs"].append(list(token.top_logprobs))
            columns["segment"].append(ASSISTANT_SEGMENT)
            columns["top_k_requested"].append(top_k)
            columns["prompt_token_count"].append(turn.prompt_token_count)
            columns["finish_reason"].append(turn.finish_reason)
            columns["model"].append(turn.model)

    table = pa.table({name: pa.array(columns[name], type=SCHEMA.field(name).type)
                      for name in SCHEMA.names}, schema=SCHEMA)
    metadata = {
        "schema_version": SCHEMA_VERSION,
        "trajectory_id": trajectory_id,
        "top_k": str(top_k),
        # Stated in the file, not just in this module: a consumer that reads
        # the sidecar without reading this source must still learn that the
        # captured mass is partial on purpose.
        "renormalized": "false",
        "tokenizer_free": "true",
        "segments": ASSISTANT_SEGMENT,
        "assistant_turns": str(len(turns)),
        "token_rows": str(table.num_rows),
    }
    if system_prompt is not None:
        # The exact context the model was conditioned on. Canonical trace
        # messages deliberately omit a harness-owned system prompt, so without
        # this the sidecar would describe a distribution over a prompt its
        # consumer cannot reconstruct.
        metadata["system_prompt"] = system_prompt
    metadata.update(extra_metadata or {})
    table = table.replace_schema_metadata(
        {METADATA_PREFIX + key: value for key, value in metadata.items()})

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    pq.write_table(table, temporary, compression="zstd")
    temporary.replace(path)
    return {
        "path": str(path),
        "tokens": table.num_rows,
        "assistant_turns": len(turns),
        "top_k": top_k,
        "bytes": path.stat().st_size,
        "sha256": file_sha256(path),
    }


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def read_metadata(path: Path) -> dict:
    """Return this sidecar's own description of itself."""
    stored = pq.read_schema(Path(path)).metadata or {}
    metadata = {}
    for key, value in stored.items():
        name = key.decode()
        if name.startswith(METADATA_PREFIX):
            metadata[name[len(METADATA_PREFIX):]] = value.decode()
    return metadata


def read_sidecar(path: Path) -> tuple[pa.Table, dict]:
    return pq.read_table(Path(path)), read_metadata(Path(path))


def summary(path: Path) -> dict:
    """Storage and shape facts, without materializing the token rows."""
    path = Path(path)
    metadata = read_metadata(path)
    parquet = pq.ParquetFile(path)
    return {
        "path": str(path),
        "bytes": path.stat().st_size,
        "tokens": parquet.metadata.num_rows,
        "top_k": int(metadata.get("top_k") or 0),
        "assistant_turns": int(metadata.get("assistant_turns") or 0),
        "schema_version": metadata.get("schema_version"),
        "renormalized": metadata.get("renormalized") == "true",
        "sha256": file_sha256(path),
    }


def assistant_turn_count(messages: list[dict]) -> int:
    return sum(1 for message in messages if message.get("role") == "assistant")


def alignment_report(messages: list[dict], path: Path) -> dict:
    """Check a sidecar against the trace it claims to describe.

    Reports rather than raises so a caller can decide what a mismatch means:
    for a build it is a reason to drop the sidecar, for a test it is the
    assertion. Misalignment is invisible downstream, so it is checked wherever
    both halves are in hand.
    """
    table, metadata = read_sidecar(Path(path))
    turns = table.column("assistant_turn_index").to_pylist()
    indices = table.column("token_index").to_pylist()
    segments = set(table.column("segment").to_pylist())
    expected_turns = assistant_turn_count(messages)

    problems: list[str] = []
    if segments - {ASSISTANT_SEGMENT}:
        problems.append(
            f"sidecar carries non-generated segments: {sorted(segments)}")
    covered = sorted(set(turns))
    if covered and (covered[0] < 1 or covered[-1] > expected_turns):
        problems.append(
            f"sidecar covers assistant turns {covered[0]}..{covered[-1]} but "
            f"the trace has {expected_turns}")
    per_turn: dict[int, list[int]] = {}
    for turn, index in zip(turns, indices):
        per_turn.setdefault(turn, []).append(index)
    for turn, positions in sorted(per_turn.items()):
        if positions != list(range(len(positions))):
            problems.append(
                f"assistant turn {turn} token indices are not a contiguous "
                f"0..n-1 run")
    return {
        "aligned": not problems,
        "problems": problems,
        "assistant_turns_in_trace": expected_turns,
        "assistant_turns_in_sidecar": len(per_turn),
        "tokens": table.num_rows,
        "top_k": int(metadata.get("top_k") or 0),
        "renormalized": metadata.get("renormalized") == "true",
    }


def manifest_entry(trajectory_id: str, relative_path: str, facts: dict) -> dict:
    """One trajectory's row in a published dataset's sidecar manifest."""
    return {
        "trajectory_id": trajectory_id,
        "path": relative_path,
        "sha256": facts.get("sha256"),
        "bytes": int(facts.get("bytes") or 0),
        "tokens": int(facts.get("tokens") or 0),
        "assistant_turns": int(facts.get("assistant_turns") or 0),
        "top_k": int(facts.get("top_k") or 0),
    }


def write_manifest(path: Path, entries: list[dict]) -> dict:
    """Write the map from published trajectory to its distributions.

    The join key a consumer needs -- ``source_trajectory_id`` and
    ``assistant_step`` -- is already in every published row, so linking the
    sidecars needs no new row column and no schema change to a dataset that
    has already been published.
    """
    ordered = sorted(entries, key=lambda entry: entry["trajectory_id"])
    document = {
        "schema_version": SCHEMA_VERSION,
        "alignment": {
            "row_key": ["source_trajectory_id", "assistant_step"],
            "sidecar_key": ["trajectory_id", "assistant_turn_index",
                            "token_index"],
            "note": ("assistant_turn_index equals the published "
                     "assistant_step; token_index runs 0..n-1 within that "
                     "assistant turn"),
        },
        "renormalized": False,
        "segments": [ASSISTANT_SEGMENT],
        "trajectories": len(ordered),
        "tokens": sum(entry["tokens"] for entry in ordered),
        "bytes": sum(entry["bytes"] for entry in ordered),
        "sidecars": ordered,
    }
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(document, indent=2) + "\n")
    temporary.replace(path)
    return document
