// Acceptance tests for the Kafka Connect REST remediation monitor.
//
// Runs a loopback fake Connect worker implementing the REST subset pinned
// in docs/contract.json. No vendor network, no real credentials. Protected:
// do not edit this file, the project file, or docs/.

using System.Net;
using System.Net.Sockets;
using System.Text;
using System.Text.Json;
using ConnectMonitor;

namespace ConnectMonitorTests;

public sealed class FakeConnectWorker : IDisposable
{
    public const string Username = "connect.ops";
    public const string Password = "dummy-cred-8e21d4"; // dummy; must never leak
    public static readonly string ExpectedAuth =
        "Basic " + Convert.ToBase64String(Encoding.UTF8.GetBytes($"{Username}:{Password}"));

    public sealed record Recorded(string Method, string Path, string Query,
        string? Auth, string? Accept);

    public List<Recorded> Requests { get; } = new();
    public string BaseUrl { get; }
    public string? RedirectStatusOf { get; set; }
    public string? RedirectTarget { get; set; }
    public (int Status, string Body)? ListFault { get; set; }

    private readonly Dictionary<string, string> _statuses = new(StringComparer.Ordinal);
    private readonly Dictionary<string, string> _infos = new(StringComparer.Ordinal);
    private readonly Dictionary<string, Queue<(int Status, string Body)>> _restartPlan =
        new(StringComparer.Ordinal);
    private readonly HttpListener _listener;
    private readonly Task _loop;

    public FakeConnectWorker()
    {
        var probe = new TcpListener(IPAddress.Loopback, 0);
        probe.Start();
        int port = ((IPEndPoint)probe.LocalEndpoint).Port;
        probe.Stop();
        BaseUrl = $"http://127.0.0.1:{port}";
        _listener = new HttpListener();
        _listener.Prefixes.Add(BaseUrl + "/");
        _listener.Start();
        _loop = Task.Run(LoopAsync);
    }

    public void AddConnector(string name, string state, string workerId, string type,
        params (int Id, string State, string WorkerId, string? Trace)[] tasks)
    {
        var taskObjs = tasks.Select(t => t.Trace is null
            ? (object)new { id = t.Id, state = t.State, worker_id = t.WorkerId }
            : new { id = t.Id, state = t.State, worker_id = t.WorkerId, trace = t.Trace })
            .ToArray();
        _statuses[name] = JsonSerializer.Serialize(new
        {
            name,
            connector = new { state, worker_id = workerId },
            tasks = taskObjs,
            type,
        });
        _infos[name] = JsonSerializer.Serialize(new
        {
            name,
            config = new Dictionary<string, string>
            {
                ["connector.class"] = "io.confluent.connect.jdbc.JdbcSinkConnector",
                ["name"] = name,
            },
            tasks = tasks.Select(t => new { connector = name, task = t.Id }).ToArray(),
            type,
        });
    }

    public void PlanRestart(string name, int status, string body)
    {
        if (!_restartPlan.TryGetValue(name, out var queue))
        {
            queue = new Queue<(int, string)>();
            _restartPlan[name] = queue;
        }
        queue.Enqueue((status, body));
    }

    public static string RestartAcceptedBody(string name, string connectorState,
        params (int Id, string State, string WorkerId)[] tasks) =>
        JsonSerializer.Serialize(new
        {
            name,
            connector = new { state = connectorState, worker_id = "w1:8083" },
            tasks = tasks.Select(t => new
            {
                id = t.Id,
                state = t.State,
                worker_id = t.WorkerId,
            }).ToArray(),
        });

    public static string ErrorBody(int code, string message) =>
        JsonSerializer.Serialize(new Dictionary<string, object>
        {
            ["error_code"] = code,
            ["message"] = message,
        });

    public List<Recorded> Restarts() =>
        Requests.Where(r => r.Method == "POST" && r.Path.EndsWith("/restart")).ToList();

    private async Task LoopAsync()
    {
        while (_listener.IsListening)
        {
            HttpListenerContext ctx;
            try { ctx = await _listener.GetContextAsync(); }
            catch (Exception) { return; }
            try { Handle(ctx); }
            catch (Exception ex)
            {
                TryRespond(ctx, 500, ErrorBody(500, "fake worker bug: " + ex.Message));
            }
        }
    }

    private void Handle(HttpListenerContext ctx)
    {
        var req = ctx.Request;
        string path = req.Url!.AbsolutePath;
        string query = req.Url!.Query.TrimStart('?');
        lock (Requests)
        {
            Requests.Add(new Recorded(req.HttpMethod, path, query,
                req.Headers["Authorization"], req.Headers["Accept"]));
        }
        if (req.Headers["Authorization"] != ExpectedAuth)
        {
            TryRespond(ctx, 401, ErrorBody(401, "Unauthorized"));
            return;
        }
        string[] parts = path.Trim('/').Split('/');
        if (req.HttpMethod == "GET" && path == "/connectors")
        {
            if (ListFault is { } fault)
            {
                TryRespond(ctx, fault.Status, fault.Body);
                return;
            }
            bool expandStatus = query.Contains("expand=status");
            bool expandInfo = query.Contains("expand=info");
            if (!expandStatus || !expandInfo)
            {
                // Without both expands the real API returns a bare name array
                // (or partial objects) — which correct clients never request.
                TryRespond(ctx, 200, JsonSerializer.Serialize(_statuses.Keys.ToArray()));
                return;
            }
            var body = new StringBuilder("{");
            bool first = true;
            foreach (var name in _statuses.Keys.OrderBy(n => n, StringComparer.Ordinal))
            {
                if (!first) body.Append(',');
                first = false;
                body.Append(JsonSerializer.Serialize(name));
                body.Append(":{\"info\":").Append(_infos[name]);
                body.Append(",\"status\":").Append(_statuses[name]).Append('}');
            }
            body.Append('}');
            TryRespond(ctx, 200, body.ToString());
        }
        else if (req.HttpMethod == "GET" && parts.Length == 3
                 && parts[0] == "connectors" && parts[2] == "status")
        {
            string name = parts[1];
            if (name == RedirectStatusOf && RedirectTarget is not null)
            {
                TryRespond(ctx, 307, "", ("Location", RedirectTarget));
                return;
            }
            if (_statuses.TryGetValue(name, out var status))
            {
                TryRespond(ctx, 200, status);
            }
            else
            {
                TryRespond(ctx, 404, ErrorBody(404, $"No status found for connector {name}"));
            }
        }
        else if (req.HttpMethod == "POST" && parts.Length == 3
                 && parts[0] == "connectors" && parts[2] == "restart")
        {
            string name = parts[1];
            if (_restartPlan.TryGetValue(name, out var queue) && queue.Count > 0)
            {
                var (status, body) = queue.Dequeue();
                TryRespond(ctx, status, body);
            }
            else
            {
                TryRespond(ctx, 204, "");
            }
        }
        else
        {
            TryRespond(ctx, 404, ErrorBody(404, "HTTP 404 Not Found"));
        }
    }

    private static void TryRespond(HttpListenerContext ctx, int status, string body,
        params (string Name, string Value)[] headers)
    {
        try
        {
            ctx.Response.StatusCode = status;
            foreach (var (name, value) in headers)
            {
                ctx.Response.Headers[name] = value;
            }
            byte[] data = Encoding.UTF8.GetBytes(body);
            if (data.Length > 0)
            {
                ctx.Response.ContentType = "application/json";
            }
            ctx.Response.ContentLength64 = data.Length;
            ctx.Response.OutputStream.Write(data);
            ctx.Response.Close();
        }
        catch (Exception)
        {
            // client went away; nothing to do
        }
    }

    public void Dispose()
    {
        try { _listener.Stop(); } catch (Exception) { }
        try { _loop.Wait(TimeSpan.FromSeconds(2)); } catch (Exception) { }
    }
}

public sealed class SilentHost : IDisposable
{
    public int Hits;
    public string BaseUrl { get; }
    private readonly HttpListener _listener;
    private readonly Task _loop;

    public SilentHost()
    {
        var probe = new TcpListener(IPAddress.Loopback, 0);
        probe.Start();
        int port = ((IPEndPoint)probe.LocalEndpoint).Port;
        probe.Stop();
        BaseUrl = $"http://127.0.0.1:{port}";
        _listener = new HttpListener();
        _listener.Prefixes.Add(BaseUrl + "/");
        _listener.Start();
        _loop = Task.Run(async () =>
        {
            while (_listener.IsListening)
            {
                try
                {
                    var ctx = await _listener.GetContextAsync();
                    Interlocked.Increment(ref Hits);
                    ctx.Response.StatusCode = 200;
                    ctx.Response.Close();
                }
                catch (Exception) { return; }
            }
        });
    }

    public void Dispose()
    {
        try { _listener.Stop(); } catch (Exception) { }
        try { _loop.Wait(TimeSpan.FromSeconds(2)); } catch (Exception) { }
    }
}

public class MonitorTests
{
    private static HttpClient NewHttp() =>
        new(new SocketsHttpHandler { AllowAutoRedirect = false });

    private static ConnectClient NewClient(FakeConnectWorker fake) =>
        new(fake.BaseUrl, FakeConnectWorker.Username, FakeConnectWorker.Password, NewHttp());

    private static void SeedMixedFleet(FakeConnectWorker fake)
    {
        fake.AddConnector("alpha", "RUNNING", "w1:8083", "source",
            (0, "RUNNING", "w1:8083", null), (1, "RUNNING", "w2:8083", null));
        fake.AddConnector("beta", "RUNNING", "w1:8083", "sink",
            (0, "RUNNING", "w1:8083", null),
            (1, "FAILED", "w2:8083",
             "org.apache.kafka.common.errors.RecordTooLargeException\n"));
        fake.AddConnector("gamma", "FAILED", "w3:8083", "sink",
            (0, "FAILED", "w3:8083", "java.lang.NullPointerException\n"));
        fake.AddConnector("delta", "PAUSED", "w1:8083", "source",
            (0, "PAUSED", "w1:8083", null));
    }

    private static void PlanMixedFleetRestarts(FakeConnectWorker fake)
    {
        fake.PlanRestart("beta", 202, FakeConnectWorker.RestartAcceptedBody(
            "beta", "RUNNING", (1, "RESTARTING", "w2:8083")));
        fake.PlanRestart("gamma", 204, "");
    }

    [Fact]
    public async Task SweepRestartsOnlyFailedConnectors()
    {
        using var fake = new FakeConnectWorker();
        SeedMixedFleet(fake);
        PlanMixedFleetRestarts(fake);
        var backoffs = new List<int>();
        var monitor = new RemediationMonitor(NewClient(fake), 2,
            (attempt, ct) => { backoffs.Add(attempt); return Task.CompletedTask; });

        var report = await monitor.RunAsync(CancellationToken.None);

        var lists = fake.Requests.Where(r => r.Path == "/connectors").ToList();
        Assert.Single(lists);
        Assert.Contains("expand=status", lists[0].Query);
        Assert.Contains("expand=info", lists[0].Query);
        Assert.DoesNotContain(fake.Requests, r => r.Path.EndsWith("/status"));
        Assert.DoesNotContain(fake.Requests, r => r.Path.Contains("/tasks/"));
        Assert.All(fake.Requests, r => Assert.Equal(FakeConnectWorker.ExpectedAuth, r.Auth));

        var restarts = fake.Restarts();
        Assert.Equal(2, restarts.Count);
        Assert.Equal("/connectors/beta/restart", restarts[0].Path);
        Assert.Equal("/connectors/gamma/restart", restarts[1].Path);
        Assert.All(restarts,
            r => Assert.Equal("includeTasks=true&onlyFailed=true", r.Query));

        Assert.Equal(new[] { "alpha", "delta" }, report.Healthy);
        Assert.Equal(6, report.Tasks.Count);
        Assert.Equal(new TaskLine("alpha", 0, "RUNNING", "w1:8083"), report.Tasks[0]);
        Assert.Equal(new TaskLine("alpha", 1, "RUNNING", "w2:8083"), report.Tasks[1]);
        Assert.Equal(new TaskLine("beta", 1, "FAILED", "w2:8083"), report.Tasks[3]);
        Assert.Equal(new TaskLine("delta", 0, "PAUSED", "w1:8083"), report.Tasks[4]);
        Assert.Equal(new TaskLine("gamma", 0, "FAILED", "w3:8083"), report.Tasks[5]);

        Assert.Equal(2, report.Actions.Count);
        Assert.Equal(new RemediationAction("beta", "RESTART_FAILED_TASKS", 1, "ACCEPTED"),
            report.Actions[0]);
        Assert.Equal(new RemediationAction("gamma", "RESTART_FAILED_TASKS", 1, "NO_CONTENT"),
            report.Actions[1]);
        Assert.Empty(backoffs);
    }

    [Fact]
    public async Task ReportIsDeterministic()
    {
        using var fake = new FakeConnectWorker();
        SeedMixedFleet(fake);
        var monitor = new RemediationMonitor(NewClient(fake), 2,
            (attempt, ct) => Task.CompletedTask);

        PlanMixedFleetRestarts(fake);
        var first = await monitor.RunAsync(CancellationToken.None);
        PlanMixedFleetRestarts(fake);
        var second = await monitor.RunAsync(CancellationToken.None);

        Assert.Equal(JsonSerializer.Serialize(first), JsonSerializer.Serialize(second));
    }

    [Fact]
    public async Task StatusEndpointParsesTaskDetail()
    {
        using var fake = new FakeConnectWorker();
        SeedMixedFleet(fake);
        var client = NewClient(fake);

        var status = await client.GetStatusAsync("beta", CancellationToken.None);

        Assert.Equal("beta", status.Name);
        Assert.Equal("RUNNING", status.State);
        Assert.Equal("w1:8083", status.WorkerId);
        Assert.Equal("sink", status.Type);
        Assert.Equal(2, status.Tasks.Count);
        Assert.Null(status.Tasks[0].Trace);
        Assert.Equal("FAILED", status.Tasks[1].State);
        Assert.StartsWith("org.apache.kafka.common.errors.RecordTooLargeException",
            status.Tasks[1].Trace);
        var recorded = fake.Requests.Single(r => r.Path == "/connectors/beta/status");
        Assert.Equal("application/json", recorded.Accept);
    }

    [Fact]
    public async Task RebalanceConflictIsRetried()
    {
        using var fake = new FakeConnectWorker();
        fake.AddConnector("eps", "FAILED", "w1:8083", "sink",
            (0, "FAILED", "w1:8083", "boom\n"));
        string conflict = FakeConnectWorker.ErrorBody(409,
            "Cannot complete request momentarily due to stale configuration " +
            "(typically caused by a concurrent config change)");
        fake.PlanRestart("eps", 409, conflict);
        fake.PlanRestart("eps", 409, conflict);
        fake.PlanRestart("eps", 202, FakeConnectWorker.RestartAcceptedBody(
            "eps", "RESTARTING", (0, "RESTARTING", "w1:8083")));
        var backoffs = new List<int>();
        var monitor = new RemediationMonitor(NewClient(fake), 3,
            (attempt, ct) => { backoffs.Add(attempt); return Task.CompletedTask; });

        var report = await monitor.RunAsync(CancellationToken.None);

        Assert.Equal(3, fake.Restarts().Count);
        Assert.Equal(new[] { 1, 2 }, backoffs);
        Assert.Equal(new RemediationAction("eps", "RESTART_FAILED_TASKS", 3, "ACCEPTED"),
            Assert.Single(report.Actions));
    }

    [Fact]
    public async Task PersistentRebalanceIsDeferredNotFatal()
    {
        using var fake = new FakeConnectWorker();
        fake.AddConnector("eps", "FAILED", "w1:8083", "sink",
            (0, "FAILED", "w1:8083", "boom\n"));
        fake.AddConnector("zeta", "RUNNING", "w2:8083", "sink",
            (0, "FAILED", "w2:8083", "later\n"));
        string conflict = FakeConnectWorker.ErrorBody(409,
            "Cannot complete request momentarily due to stale configuration");
        for (int i = 0; i < 3; i++)
        {
            fake.PlanRestart("eps", 409, conflict);
        }
        var backoffs = new List<int>();
        var monitor = new RemediationMonitor(NewClient(fake), 2,
            (attempt, ct) => { backoffs.Add(attempt); return Task.CompletedTask; });

        var report = await monitor.RunAsync(CancellationToken.None);

        Assert.Equal(new[] { 1, 2 }, backoffs);
        Assert.Equal(2, report.Actions.Count);
        Assert.Equal(new RemediationAction("eps", "RESTART_FAILED_TASKS", 3,
            "REBALANCE_DEFERRED"), report.Actions[0]);
        Assert.Equal(new RemediationAction("zeta", "RESTART_FAILED_TASKS", 1,
            "NO_CONTENT"), report.Actions[1]);
    }

    [Fact]
    public async Task VanishedConnectorDoesNotAbortTheSweep()
    {
        using var fake = new FakeConnectWorker();
        fake.AddConnector("ghost", "FAILED", "w1:8083", "sink",
            (0, "FAILED", "w1:8083", "gone\n"));
        fake.AddConnector("keeper", "RUNNING", "w2:8083", "sink",
            (0, "FAILED", "w2:8083", "flaky\n"));
        fake.PlanRestart("ghost", 404,
            FakeConnectWorker.ErrorBody(404, "Unknown connector: ghost"));
        var monitor = new RemediationMonitor(NewClient(fake), 2,
            (attempt, ct) => Task.CompletedTask);

        var report = await monitor.RunAsync(CancellationToken.None);

        Assert.Equal(2, report.Actions.Count);
        Assert.Equal(new RemediationAction("ghost", "RESTART_FAILED_TASKS", 1,
            "NOT_FOUND"), report.Actions[0]);
        Assert.Equal(new RemediationAction("keeper", "RESTART_FAILED_TASKS", 1,
            "NO_CONTENT"), report.Actions[1]);
    }

    [Fact]
    public async Task RedirectsAreRefusedAndCredentialsStayHome()
    {
        using var fake = new FakeConnectWorker();
        using var evil = new SilentHost();
        SeedMixedFleet(fake);
        fake.RedirectStatusOf = "beta";
        fake.RedirectTarget = evil.BaseUrl + "/connectors/beta/status";
        var client = NewClient(fake);

        var ex = await Assert.ThrowsAsync<ConnectApiException>(
            () => client.GetStatusAsync("beta", CancellationToken.None));

        Assert.Equal(307, ex.HttpStatus);
        Assert.Equal(0, evil.Hits);
    }

    [Fact]
    public async Task ErrorEnvelopeIsSurfaced()
    {
        using var fake = new FakeConnectWorker();
        fake.ListFault = (500, FakeConnectWorker.ErrorBody(500,
            "Request timed out"));
        var client = NewClient(fake);

        var ex = await Assert.ThrowsAsync<ConnectApiException>(
            () => client.ListConnectorsAsync(CancellationToken.None));

        Assert.Equal(500, ex.HttpStatus);
        Assert.Contains("Request timed out", ex.Message);
    }
}
